### ISSUE TITLE
Serilog integration makes app hang on MAUI

### ISSUE THREAD

**Issue by modplug** [getsentry/sentry-dotnet#3451] opened 2024-06-26 07:11 UTC
### Package

Sentry.Serilog

### .NET Flavor

Other

### .NET Version

8.0.0

### OS

iOS

### SDK Version

4.7.0

### Steps to Reproduce

# Issue: App Hangs When Integrating Sentry Serilog Logger in MAUI Project

## Description

While integrating the Sentry Serilog logger into a new MAUI project, the application hangs, and an error is printed in the console.

## Steps to Reproduce

1. Create a new MAUI project.
2. Configure the Serilog logger with the Sentry sink as shown below:

    ```csharp
    .WriteTo.Sentry(o =>
    {
        o.Environment = settings.AppEnvironment.ToString();
        o.MinimumBreadcrumbLevel = LogEventLevel.Information;
        o.MinimumEventLevel = LogEventLevel.Warning;
        o.Dsn = settings.SentryDsn;
    })
    ```

3. Run the application. Observe that the app hangs and the following error message appears in the console:

    ```
    Error: Error getting MAUI device information.
    UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.
    at UIKit.UIApplication.EnsureUIThread() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 111
    at UIKit.UIScreen.get_MainScreen() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIScreen.g.cs:line 401
    at Microsoft.Maui.Devices.DeviceDisplayImplementation.GetMainDisplayInfo()
    at Microsoft.Maui.Devices.DeviceDisplayImplementationBase.get_MainDisplayInfo()
    at Microsoft.Maui.Devices.DeviceDisplay.get_MainDisplayInfo()
    at Sentry.Maui.Internal.MauiDeviceData.ApplyMauiDeviceData(Device device, IDiagnosticLogger logger)
    ```

## Additional Information

The issue seems to stem from the `Microsoft.Maui.Devices.DeviceDisplay` implementation, which attempts to access `UIScreen.MainScreen` from a non-UI thread when the Sentry logger is configured.

### Expected Result

The application should run without hanging, and the Sentry Serilog logger should correctly capture logs without causing threading issues.

### Actual Result

The application hangs, and an exception related to UIKit thread access is printed in the console, indicating that a UIKit method is being called from a non-UI thread.
The error seems to get catched, but the app still hangs.

**Comment by bitsandfoxes** [comment] 2024-06-26 16:36
Thanks for the detailed issue! We're going to take it from here!

**Comment by bitsandfoxes** [comment] 2024-06-26 16:37
Just to make sure I've got everything: You're just using the serilog integration in your MAUI application? Or is this in combination with the Sentry.MAUI package?

**Comment by modplug** [comment] 2024-06-26 16:39
The error happens when using both Sentry SDK and Sentry Serilog packages in a MAUI project

**Comment by jamescrosswell** [comment] 2024-06-27 02:19
> ```cs
> .WriteTo.Sentry(o =>
> {
>     o.Environment = settings.AppEnvironment.ToString();
>     o.MinimumBreadcrumbLevel = LogEventLevel.Information;
>     o.MinimumEventLevel = LogEventLevel.Warning;
>     o.Dsn = settings.SentryDsn;
> })
> ```

@modplug if you've initialised Sentry via the Maui integration then you'll want to use the non-initializing overload of `WriteTo` to configure the SeriLog integration. 

For details, see:
- https://github.com/getsentry/sentry-dotnet/pull/2928

**Comment by modplug** [comment] 2024-06-28 07:44
Thanks for the tip, @jamescrosswell.

I'm trying to set up the logger as early as possible in my MauiProgram
```csharp
Logger
.WriteTo.Sentry(o =>
                {
                    o.InitializeSdk = false;
                    o.Environment = settings.AppEnvironment.ToString();
                    o.MinimumBreadcrumbLevel = LogEventLevel.Information;
                    o.MinimumEventLevel = LogEventLevel.Warning;
                })
                
 AppBuilder
.UseSentry(options =>
            {
                options.Environment = settings.AppEnvironment.ToString();
                options.Dsn = settings.SentryDsn;
                options.Debug = settings.AppEnvironment == AppEnvironment.Debug;
                options.AttachScreenshot = true;
            })
            
 ```
 This is how I've set up my Sentry integration. 
 I'm still getting occasional hangs and this is the error that shows up in Sentry:

App Hanging: App hanging for at least 2000 ms.

The last thing I see in my stack trace is this error:

```
Error: Error getting MAUI device information.
UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.
at UIKit.UIApplication.EnsureUIThread() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 111
at UIKit.UIScreen.get_MainScreen() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIScreen.g.cs:line 401
at Microsoft.Maui.Devices.DeviceDisplayImplementation.GetMainDisplayInfo()
at Microsoft.Maui.Devices.DeviceDisplayImplementationBase.get_MainDisplayInfo()
at Microsoft.Maui.Devices.DeviceDisplay.get_MainDisplayInfo()
at Sentry.Maui.Internal.MauiDeviceData.ApplyMauiDeviceData(Device device, IDiagnosticLogger logger)

**Comment by jamescrosswell** [comment] 2024-07-01 09:09
> I'm still getting occasional hangs and this is the error that shows up in Sentry:
> 
> App Hanging: App hanging for at least 2000 ms.

Hey @modplug . You could disable app hang tracking if this isn't proving reliable for you. We have a sample that illustrates enabling this - disabling is just a matter of setting to false instead of true:

https://github.com/getsentry/sentry-dotnet/blob/9b60486bbe41c31c3e54b55ec728cc28a2891346/samples/Sentry.Samples.Ios/AppDelegate.cs#L25

Alternatively, you could leave it enabled but change how long things have to be unresponsive before being considered "hung", via the `AppHangTimeoutInterval` option.

**Comment by exquirentibus** [comment] 2024-09-02 02:47
I am also getting the App hanging for at least 2000 ms. issue with .NET8 Maui on IOS.

My AppDelegate.cs in Maui is very different than the one you link to?   Other than the code I have for Shiny.net push notifications, this is my AppDelegate.cs.   It seems to be completely different from yours?

```
using Foundation;
using UIKit;

namespace MauiDiag {
    [Register("AppDelegate")]
    public class AppDelegate : MauiUIApplicationDelegate {
        protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp(); // call during app startup
}}
```

how exactly do I modify that to incorporate the properties for increasing the hang timeout or disabling it into the AppDelegate.cs?

Is there no way to do this inside .UseSentry(options => {

with some code vaguely resembling:

```
var sentryOptions = options as SentryOptions;

if (sentryOptions != null) {
   sentryOptions.AppHangTimeoutInterval = TimeSpan.FromMilliseconds(4000);  // Increase hang timeout
   sentryOptions.DisableAppHangTracking = true;  // Disable hang tracking
}
```

**Comment by jamescrosswell** [comment] 2024-09-02 04:00
> how exactly do I modify that to incorporate the properties for increasing the hang timeout or disabling it into the AppDelegate.cs?

@exquirentibus that's the same way the AppDelegate has been declared in the Sentry sample app:
https://github.com/getsentry/sentry-dotnet/blob/7e4ca2ce517142454e659ddbe08a8cd2b8cd8233/samples/Sentry.Samples.Maui/Platforms/iOS/AppDelegate.cs#L8

All it's doing is calling `MauiProgram.CreateMauiApp()` which is where all the logic to create the MauiApp is contained (and where the [logic to initialise/configure Sentry](https://github.com/getsentry/sentry-dotnet/blob/a8583e136802d9d664fe22ae6674719287bd82d2/samples/Sentry.Samples.Maui/MauiProgram.cs#L10-L25) is contained).

**Comment by exquirentibus** [comment] 2024-09-02 15:14
> > how exactly do I modify that to incorporate the properties for increasing the hang timeout or disabling it into the AppDelegate.cs?
> 
> [@exquirentibus](https://github.com/exquirentibus) that's the same way the AppDelegate has been declared in the Sentry sample app:
> 
> [sentry-dotnet/samples/Sentry.Samples.Maui/Platforms/iOS/AppDelegate.cs](https://github.com/getsentry/sentry-dotnet/blob/7e4ca2ce517142454e659ddbe08a8cd2b8cd8233/samples/Sentry.Samples.Maui/Platforms/iOS/AppDelegate.cs#L8)
> 
> Line 8 in [7e4ca2c](/getsentry/sentry-dotnet/commit/7e4ca2ce517142454e659ddbe08a8cd2b8cd8233)
>  protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp(); 
> 
> All it's doing is calling `MauiProgram.CreateMauiApp()` which is where all the logic to create the MauiApp is contained (and where the [logic to initialise/configure Sentry](https://github.com/getsentry/sentry-dotnet/blob/a8583e136802d9d664fe22ae6674719287bd82d2/samples/Sentry.Samples.Maui/MauiProgram.cs#L10-L25) is contained).

Then are you saying there is code I can add to the [logic to initialise/configure Sentry](https://github.com/getsentry/sentry-dotnet/blob/a8583e136802d9d664fe22ae6674719287bd82d2/samples/Sentry.Samples.Maui/MauiProgram.cs#L10-L25)? I still am unclear on how to add that within MauiProgram.cs?   At least the logic to disable checking for app hanging or to increase the AppHangTimeoutInterval?

**Comment by jamescrosswell** [comment] 2024-09-02 21:50
> Then are you saying there is code I can add to the [logic to initialise/configure Sentry](https://github.com/getsentry/sentry-dotnet/blob/a8583e136802d9d664fe22ae6674719287bd82d2/samples/Sentry.Samples.Maui/MauiProgram.cs#L10-L25)? I still am unclear on how to add that within MauiProgram.cs? At least the logic to disable checking for app hanging or to increase the AppHangTimeoutInterval?

Exactly. The code you linked to there is a callback that you can define, which gets passed a `SentryOptions` instance. That object has an `AppHangTimeoutInterval` property that you can set to control how long the app has to hang before it becomes an `issue` in Sentry.

**Comment by exquirentibus** [comment] 2024-09-02 23:04
> > Then are you saying there is code I can add to the [logic to initialise/configure Sentry](https://github.com/getsentry/sentry-dotnet/blob/a8583e136802d9d664fe22ae6674719287bd82d2/samples/Sentry.Samples.Maui/MauiProgram.cs#L10-L25)? I still am unclear on how to add that within MauiProgram.cs? At least the logic to disable checking for app hanging or to increase the AppHangTimeoutInterval?
> 
> Exactly. The code you linked to there is a callback that you can define, which gets passed a `SentryOptions` instance. That object has an `AppHangTimeoutInterval` property that you can set to control how long the app has to hang before it becomes an `issue` in Sentry.

I'm sorry?  I must be very dense as you seem to be suggesting that I can do this:

```
 .UseSentry(options => {
     options.Dsn = "myDsn";
     options.Debug = true;
     options.TracesSampleRate = 1.0;
     options.AppHangTimeoutInterval = TimeSpan.FromMilliseconds(4000);
```

whereas this won't build in Maui as I get this build error:

'SentryMauiOptions' does not contain a definition for 'AppHangTimeoutInterval' and no accessible extension method 'AppHangTimeoutInterval' accepting a first argument of type 'SentryMauiOptions' could be found (are you missing a using directive or an assembly reference?)

**Comment by jamescrosswell** [comment] 2024-09-03 00:12
> whereas this won't build in Maui as I get this build error:
> 
> 'SentryMauiOptions' does not contain a definition for 'AppHangTimeoutInterval'

If you haven't written applications that target multiple frameworks before, this can be a bit confusing. In your project file you likely have something that looks like this:
```xml
        <TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
```

That means when you "build" your app, you're actually building it multiple times (one for each of those TargetFrameworks). 

The `AppHangTimeoutInterval` property only exists for iOS, so your code can only refer to this when targeting iOS. .NET creates a couple of compiler directives that you can use to create conditional code blocks though... so what you want to do is this:

```csharp
 .UseSentry(options => {
     options.Dsn = "myDsn";
     options.Debug = true;
     options.TracesSampleRate = 1.0;
#if IOS
     options.AppHangTimeoutInterval = TimeSpan.FromMilliseconds(4000);
#endif
```

That way your code only tries to refer to the iOS only `AppHangTimeoutInterval` property when building the iOS version of your app.

Alternatively, if you don't care about targeting other platforms, you could remove those target frameworks from your csproj file and only target iOS... then you wouldn't need any conditional compilation blocks.

**Comment by exquirentibus** [comment] 2024-09-03 02:16
> The `AppHangTimeoutInterval` property only exists for iOS, so your code can only refer to this when targeting iOS. .NET creates a couple of compiler directives that you can use to create conditional code blocks though... so what you want to do is this:
> 
>  .UseSentry(options => {
>      options.Dsn = "myDsn";
>      options.Debug = true;
>      options.TracesSampleRate = 1.0;
> #if IOS
>      options.AppHangTimeoutInterval = TimeSpan.FromMilliseconds(4000);
> #endif

James - yes .. that makes perfect sense.  I use #if extensively for IOS and ANDROID and WINDOWS.

I tried your suggestions exactly (encasing it in #if #end) but I'm still getting this error??

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS1061	'SentryMauiOptions' does not contain a definition for 'AppHangTimeoutInterval' and no accessible extension method 'AppHangTimeoutInterval' accepting a first argument of type 'SentryMauiOptions' could be found (are you missing a using directive or an assembly reference?)	MauiDiag (net8.0-ios)	G:\VS Projects\GrpcService\MauiDiag\MauiProgram.cs	68	

Possibly I can't nest as I have this nested and I don't remember nesting before?

```
#if SENTRY
                // Add this section anywhere on the builder:
                .UseSentry(options => {
                    // The DSN is the only required setting.
                    options.Dsn = "myDsn";

                     options.Debug = true;

                    options.TracesSampleRate = 1.0;

#if IOS
                    options.AppHangTimeoutInterval = TimeSpan.FromMilliseconds(4000);
#endif

                  })
#endif
```

**Comment by jamescrosswell** [comment] 2024-09-03 07:28
Sorry, that should be `options.Native.AppHangTimeoutInterval = TimeSpan.FromMilliseconds(4000);`

**Comment by exquirentibus** [comment] 2024-09-03 14:28
> options.Native.AppHangTimeoutInterval = TimeSpan.FromMilliseconds(4000);

Ahhhh!  Thank you so much!!  Problem solved!!   

I'd noticed an options.Android and looked for options.IOS.    I just didn't associate Native with IOS?

**Comment by bitsandfoxes** [comment] 2024-09-04 13:43
> I'd noticed an options.Android and looked for options.IOS. I just didn't associate Native with IOS?

Yeah, this is not ideal. Having to keep all those layers in mind if all you want to do with MAUI is to not think about the platforms is a pain.

**Comment by bitsandfoxes** [comment] 2024-09-04 13:45
Getting back to the original issue: Could this be related to https://github.com/getsentry/sentry-dotnet/pull/3521?

The stacktrace mentions device display as well
```
Error: Error getting MAUI device information.
UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.
at UIKit.UIApplication.EnsureUIThread() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 111
at UIKit.UIScreen.get_MainScreen() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIScreen.g.cs:line 401
at Microsoft.Maui.Devices.DeviceDisplayImplementation.GetMainDisplayInfo()
at Microsoft.Maui.Devices.DeviceDisplayImplementationBase.get_MainDisplayInfo()
at Microsoft.Maui.Devices.DeviceDisplay.get_MainDisplayInfo()
at Sentry.Maui.Internal.MauiDeviceData.ApplyMauiDeviceData(Device device, IDiagnosticLogger logger)
```

**Comment by jamescrosswell** [comment] 2024-09-24 06:35
> Getting back to the original issue: Could this be related to [#3521](https://github.com/getsentry/sentry-dotnet/pull/3521)?

Possibly. I'm not able to reproduce the original problem that was reported however (new Maui App targeting `net8.0`, initialising Sentry via the Serilog integration). 

I think we close this issue and reopen if/when we have a way to reliably reproduce.

**Closed by jamescrosswell** 2024-09-24 06:35 UTC
Labels: Bug, Serilog, MAUI
