### ISSUE TITLE
.NET MAUI App Crashes on iPhone Deployment with Sentry

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry-dotnet#3615] opened 2024-09-18 21:39 UTC
### Package

Sentry.Maui

### .NET Flavor

.NET Framework

### .NET Version

8.0.8

### OS

iOS

### SDK Version

4.10.2

### Steps to Reproduce

**Description:** 
A customer reports that their .NET MAUI application crashes when deployed to a physical iPhone in Release mode after integrating Sentry (v4.10.2). They've mentioned the crash occurs when querying a SQLite database using Entity Framework Core 8.0.8. 

Additional information:
Crash only occurs in Release mode on a real iPhone (or occasionally in iOS Simulator). Removing Sentry from the project prevents the crash. The crash results in the following Sentry error: EXC_BAD_ACCESS/AppleCryptoNative_GetRandomBytes.

Repro app and steps in support ticket: https://sentry.zendesk.com/agent/tickets/132032

### Expected Result

App should continue running after the database query without crashing.

### Actual Result

The app crashes in Release mode when deployed to a real iPhone after the database query. No crash occurs in Debug mode or when Sentry is removed from the project.

**Comment by bruno-garcia** [comment] 2024-09-18 21:45
Thanks for the context, we'll look into it asap!

**Comment by bruno-garcia** [comment] 2024-09-18 21:59
It only crashes in Release mode likely because it's only doing AOT on Release mode. Afaik Debug mode has an interpreter mode.

`AppleCryptoNative_GetRandomBytes` is .NET code ([see this comment](https://github.com/dotnet/runtime/issues/106377#issuecomment-2287745220)) it seems, and the bug might be there. And we might need to raise with Microsoft.

For that we'd need a repro that can be run without licenses dependencies (e.g: DevExpress).

I mean if the crash doesn't happen without Sentry, there's a chance it's some swizzling we do on DB queries (SQLite integration). We can try [disabling all swizzling code](https://docs.sentry.io/platforms/apple/configuration/swizzling/) to narrow down if that's the case. Shouldn't crash anymore even with Sentry installed in that case.

**Comment by MAUIoxo** [comment] 2024-09-20 10:07
I tried it with the following configurations in the .csproj:

```xml
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <Optimize>true</Optimize>
    <AotAssemblies>false</AotAssemblies>
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchUseLlvm>true</MtouchUseLlvm>
    <MtouchInterpreter>none</MtouchInterpreter>
</PropertyGroup>
```

and also **with AOT-Compilation**:

```xml
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <Optimize>true</Optimize>
    <AotAssemblies>true</AotAssemblies>
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchUseLlvm>true</MtouchUseLlvm>
    <MtouchInterpreter>none</MtouchInterpreter>
</PropertyGroup>
```

Both did **not crash**!

Something like the following setting **crashed**:

```xml
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <Optimize>true</Optimize>
    <AotAssemblies>true</AotAssemblies>
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchUseLlvm>true</MtouchUseLlvm>
    <MtouchInterpreter>-all</MtouchInterpreter>		
</PropertyGroup>
```

<br/>
<br/>

The situation now is a bit different. I don’t know what changed, but since the latest update of **Visual Studio** to version **17.11.4**, I could not reproduce this anymore with the original example whereas before it was reproducible with the settings from the example and adapted configurations above!

It behaved like when creating an intentional `NullReferenceException` in a `try-catch`-Block.

Anyway, if it still makes sense for you, I could try to get Symbols from the original example. If you could tell me what exactly I should do to get the relevant information you need. But just, if it still makes sense.

Other than that, we could also close this issue and if I get this behavior again we reopen it?

**Comment by jamescrosswell** [comment] 2024-09-23 01:49
Thanks @MAUIoxo - let's close this issue for now. If it pops up again, we can always reopen.

**Closed by jamescrosswell** 2024-09-23 01:49 UTC
Labels: Bug, MAUI
