### ISSUE TITLE
Unable to build MAUI application for iOS

### ISSUE THREAD

**Issue by pikausp** [getsentry/sentry-dotnet#2391] opened 2023-05-24 14:59 UTC
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

7.0.302

### OS

iOS

### SDK Version

3.33.0

### Steps to Reproduce

Attempt to debug the application found https://github.com/pikausp/SentryMauiRepro on a remote (connected to Mac) iPhone.

### Expected Result

The application is successfully deployed and debugging starts.

### Actual Result

The build fails with the following error

```
Build started...
1>------ Build started: Project: SentryMauiRepro, Configuration: Release Any CPU ------
1>Executing SayHello Task to establish a connection to a Remote Server. 
1>			Properties: 
1>				SessionId=6eaa184a2531710eadd0e538496d7006fd9b8035b5bdacf9a6e11e4424e7022b, 
1>				Addresss=192.168.0.144, 
1>				SshPort=22, 
1>				TcpPort=54990, 
1>				User=macUser, 
1>				AppName=SentryMauiRepro,
1>				VisualStudioProcessId=48640,
1>				ContinueOnDisconnected=False
1>Executing SayHello Task to establish a connection to a Remote Server. 
1>			Properties: 
1>				SessionId=6eaa184a2531710eadd0e538496d7006fd9b8035b5bdacf9a6e11e4424e7022b, 
1>				Addresss=192.168.0.144, 
1>				SshPort=22, 
1>				TcpPort=54990, 
1>				User=macUser, 
1>				AppName=SentryMauiRepro,
1>				VisualStudioProcessId=48640,
1>				ContinueOnDisconnected=False
1>Detected signing identity:
1>  Code Signing Key: "Apple Development: Created via API (******)" (******)
1>  Provisioning Profile: "VS: WildCard Development" (******)
1>  Bundle Id: com.companyname.sentrymauirepro
1>  App Id: ******.com.companyname.sentrymauirepro
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error : MessagingRemoteException: An error occurred on client Build1647054 while executing a reply for topic xvs/build/16.4.7054/execute-task/SentryMauiRepro/6eaa184002fGetFileSystemEntries
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error : DirectoryNotFoundException: Could not find a part of the path '/Users/macUser/Library/Caches/Xamarin/mtbs/builds/SentryMauiRepro/6eaa184a2531710eadd0e538496d7006fd9b8035b5bdacf9a6e11e4424e7022b/C:/Users/pikau/.nuget/packages/sentry.bindings.cocoa/3.33.0/lib/net6.0-ios16.1/Sentry.Bindings.Cocoa.resources'.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error :
1>Done building project "SentryMauiRepro.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 4:48 PM and took 12.835 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy started at 4:48 PM and took 12.835 seconds ==========
```

**Comment by mattjohnsonpint** [comment] 2023-05-25 06:42
Thanks for reporting.  Can you please do `dotnet workload update` from both the Mac and Windows side (or use VS Installer to update) before I dig further?  "Pair to mac" issues can be difficult to investigate, and I'd like to make sure there's not something already resolved from Microsoft before moving forward.

In the meantime, you should still be able to deploy with the "Hot Restart" option by connecting the iPhone directly to the Windows machine - or by developing completely on the Mac side.

As a library developer, having to provide workarounds to support all of these different deployment paths has been quite challenging.  Thanks for your understanding.

**Comment by mattjohnsonpint** [comment] 2023-05-25 06:46
This is also in the way to debug at the moment: https://developercommunity.visualstudio.com/t/After-Visual-Studio-1751-update-Xamari/10301221

**Comment by pikausp** [comment] 2023-05-25 08:41
Sadly I cannot use Hot Restart due to the challenges it poses. We have a dependency on Realm database which does not support deployment via Hot Restart :(

After running `dotnet workload update` on my Windows workstation I cannot even connect to the Mac anymore. I get the following error
`The connection cannot continue because the remote iOS SDK was not found or is corrupted. If the issue persists, please try removing the `~/Library/Caches/Xamarin/XMA/SDKs/dotnet/` folder on the Mac and try again`

I tried the suggestion, didn't work. I then reset the Mac completely, didn't work either. Ended up reinstalling Visual Studio, but I'm still getting the same error. 

I will update you when I manage to get past this error.

**Comment by pikausp** [comment] 2023-05-25 09:11
Okay, what helped was to install the preview version of VS, and connect, this started installing some missing dependencies. Then when I connected with the regular VS instance it started installing missing dependencies for the non-preview version.

After this, when I attempt to deploy and launch the application I get the error I posted originally about `sentry.bindings.cocoa` folder missing on the Mac.

**Comment by mattjohnsonpint** [comment] 2023-05-25 12:01
Would it be possible to provide a binlog?  In this setup, the easiest way to record one is to use the [VS extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022).

Thanks.

**Comment by mattjohnsonpint** [comment] 2023-05-25 12:08
Also, just for setting expectations - I'm at a conference this week, so it will be next week before I can attempt to reproduce this.  Thanks.

**Comment by pikausp** [comment] 2023-05-25 14:05
I got the binlog. Are there any secrets included or can I just attach it here?

Secondly, thank you for letting me know.

**Comment by mattjohnsonpint** [comment] 2023-05-26 07:56
It will include anything that is emitted as build output.  If you're concerned about potential leaking secrets, then I suggest building a separate application to reproduce the problem and sending output of that.  You can either past a zip of the binlog here, or if you prefer you can email it to me at matt.johnson-pint@sentry.io or contact me on the `#dotnet` channel on our [Community Discord](https://discord.com/invite/Ww9hbqr).

**Comment by mattjohnsonpint** [comment] 2023-05-26 07:57
If you want to view the binlog yourself to see what's in it (search, etc.) you can use the MS binlog viewer https://msbuildlog.com/

**Comment by mattjohnsonpint** [comment] 2023-05-26 10:35
I'm wondering if it might be the same as this: https://github.com/xamarin/xamarin-macios/issues/18308

**Comment by pikausp** [comment] 2023-05-26 18:24
I can confirm I manually removed the line where `SessionId` is set as instructed in this comment https://github.com/xamarin/xamarin-macios/issues/18308#issuecomment-1559808140 and after restarting Visual Studio I am able to build and deploy the repro project and my regular project.

**Comment by mattjohnsonpint** [comment] 2023-05-26 19:38
Awesome. Glad there's a workaround, and looks like it will be fixed directly by Microsoft soon enough.  Thanks for the details!

**Closed by mattjohnsonpint** 2023-05-26 19:38 UTC
Labels: bug, MAUI, iOS, Platform: .NET

**Comment by philipag** [comment] 2023-08-03 07:00
For anyone else encountering the error "The connection cannot continue because the remote iOS SDK was not found or is corrupted" when connecting to the mac:

In my case it was caused by having removed "net7.0-ios" from csproj TargetFrameworks (because I was working mostly on Android at the time).  Adding it back made VS install all the dependencies and connect successfully.

**Comment by czmirek** [comment] 2024-02-23 11:32
If you accidentaly unload or forget to reload your .NET MAUI project you'll get this error as well.

**Comment by RedZone908** [comment] 2024-06-04 17:54
I second @philipag 's answer, that was definitely my problem. Though it was .net8-ios by now. It would be really really nice if the log told you "hey don't connect to the Mac from an Android-only project" rather than giving you a cryptic error that seems to mean nothing
