### ISSUE TITLE
The `System.ObjectDisposed` exception is thrown when applying clipping to an element in MAUI

### ISSUE THREAD

**Issue by ashok-kuvaraja** [getsentry/sentry-dotnet#2996] opened 2023-12-29 11:08 UTC
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

8.0

### OS

macOS

### SDK Version

3.41.3

### Steps to Reproduce

In the provided sample, I have arranged elements in the vertical direction with virtualization support. While scrolling and applying clipping to an element, I encountered the `System.ObjectDisposed` exception. The application functions perfectly without integrating the Sentry package into the `MauiAppBuilder`, and the exception doesn't occur if I refrain from applying a clip to an element. However, it is required to apply clipping to an element in my scenario.

To reproduce the issue:

1. Run the sample below.
2. Scroll vertically to the end.

[MauiApplication.zip](https://github.com/getsentry/sentry-dotnet/files/13792808/MauiApplication.zip)

**Note:** Make sure to add `Dsn` link in the `MauiProgram.cs` file

### Expected Result

It should be worked without any exception

### Actual Result

The app has crashed with `System.ObjectDisposed` exception. Find the demo below,

https://github.com/getsentry/sentry-dotnet/assets/60499432/b7219193-ee95-4280-810e-7969facf413a

**Comment by bitsandfoxes** [comment] 2024-01-04 17:21
Thanks a lot for the repro! I'm looking into this!

**Comment by bitsandfoxes** [comment] 2024-01-11 14:51
I suspect this has to do with the way the SDK used to hook itself up for breadcrumb creation as I cannot reproduce this with the current `4.0.0` version of the SDK.

**Comment by bitsandfoxes** [comment] 2024-01-11 15:45
Confirmed by checking with the old SDK. Fixed by https://github.com/getsentry/sentry-dotnet/pull/2900

**Closed by bitsandfoxes** 2024-01-11 15:45 UTC
Labels: Bug, MAUI, Platform: .NET
