### ISSUE TITLE
Idle Transactions

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#1770] opened 2022-07-08 15:57 UTC
### Problem Statement

The idea is to have transactions that do not have a specified ending but a timeout instead.

### Solution Brainstorm

This could be achieved by extending `TransactionTracer` with an optional parameter for the timeout. This should work independently of `wait for children` and simply trigger a finish after a set time period.

Other SDKs implementation of this: 
- Cocoa: https://github.com/getsentry/sentry-cocoa/blob/d2076a999d23fff77ff5736d6ae7c6734e49b8e0/Sources/Sentry/SentryTracer.m#L97
- Dart: https://github.com/getsentry/sentry-dart/blob/a5e904f5a26ffdfc8b6065a68c6152ea936b0644/dart/lib/src/sentry_tracer.dart#L43
- Java: https://github.com/getsentry/sentry-java/blob/fa3886ffaae668ef2e5d57783df89bfd8bb0c6bb/sentry/src/main/java/io/sentry/SentryTracer.java#L100

**Comment by bruno-garcia** [comment] 2022-07-08 16:08
Dupe of: https://github.com/getsentry/sentry-dotnet/issues/1074 ?

**Comment by mattjohnsonpint** [comment] 2022-07-13 22:22
Will track in #1074.  Thanks.

**Closed by mattjohnsonpint** 2022-07-13 22:22 UTC
Labels: enhancement, Platform: .NET

**Comment by bruno-garcia** [comment] 2022-07-13 22:27
Moved the details from here over there with additional context and links: https://github.com/getsentry/sentry-dotnet/issues/1074
