### ISSUE TITLE
Trying to get a span of type Execution

### ISSUE THREAD

**Issue by STRATZ-Ken** [getsentry/sentry-dotnet#1210] opened 2021-09-23 12:50 UTC
### Environment

How do you use Sentry?
On-Premise (21.9.0)

Which SDK and version?
.Net 5.0.10

### Steps to Reproduce

Hello, I just recently upgraded from .Net 3.X to 5.0.  I also upgraded my Sentry server and Sentry API to the latest version. (3.9.3  Client & 21.9.0).  However, I noticed that the amount of WARN logs (NLog) I am getting  from ISentry client is insane. I did not get these errors previously. 

It looks like from GitHub this is coming from an SQL logger in Sentry.

Some other things to mention, its an API Server. I use GraphQL, Entity Framework and some very light Dapper.

```
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id f85667cd-5b41-434a-a3f1-51f33c261377, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Connection with operation id , but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id e04a4161-f20d-483b-bb1b-1eb09dd73be1, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Connection with operation id , but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id 7b70e129-e5e4-4979-8a7a-5ac4dc2204d2, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Connection with operation id , but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id 50ad4d85-4083-4ca2-aadb-206f56a2e1b7, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Connection with operation id , but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id 86900659-28bf-4f00-8ff5-5b1469cfa537, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Connection with operation id , but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id faa466e5-52af-4406-a51f-18e2a4a2d89d, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Connection with operation id , but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id 09329ca3-16d4-4115-b565-d215d416cc8d, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id a86f6f49-ff0c-4d28-a9b6-4865008dc143, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Execution with operation id 75ff00e2-a480-4192-a7a1-8a3d701e2c46, but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Connection with operation id , but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
WARN|Sentry.ISentryClient|Trying to get a span of type Connection with operation id , but it was not found.||Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|SentryScopeManager.ConfigureScope => <>c__DisplayClass31_0.<GetSpan>b__0 => MelDiagnosticLogger.Log
```

**Comment by STRATZ-Ken** [comment] 2021-09-23 14:58
I also just found this in the boot log.

```
2021-09-23 07:48:38.7490|ERROR|Sentry.ISentryClient|Failed to find BootTime: Now 9/23/2021 2:48:38 PM +00:00, GetTimestamp 44063960953182, Frequency 2246097, TicksPerSecond: 10000000|Attempted to divide by zero.|Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|DiagnosticLoggerExtensions.LogError => DiagnosticLoggerExtensions.LogIfEnabled => MelDiagnosticLogger.Log
2021-09-23 07:48:40.8593|ERROR|Sentry.ISentryClient|Failed to find BootTime: Now 9/23/2021 2:48:40 PM +00:00, GetTimestamp 44063965701878, Frequency 2246097, TicksPerSecond: 10000000|Attempted to divide by zero.|Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|DiagnosticLoggerExtensions.LogError => DiagnosticLoggerExtensions.LogIfEnabled => MelDiagnosticLogger.Log
```

**Comment by lucas-zimerman** [comment] 2021-09-23 16:38
Hi STRATZ-Ken, thank you for your report!

Just some clarifications, are you using the .NET SDK or the ASP.NET Core SDK?

And are you creating Transactions using SentrySdk.StartTransaction or using another method?

**Comment by STRATZ-Ken** [comment] 2021-09-23 16:41
Just some clarifications, are you using the .NET SDK or the ASP.NET Core SDK?

- ASP.Net Core SDK

And are you creating Transactions using SentrySdk.StartTransaction or using another method?

- I do not use this feature right now.  Just to capture GraphQL exceptions.
- 
```
Sentry.SentrySdk.WithScope(t =>
                    {
                        t.SetExtra("query", ctx.Context.Document.OriginalQuery);
                        t.SetExtra("variables", ctx.Context.Variables);
                        Sentry.SentrySdk.CaptureException(ctx.OriginalException);
                    });
```

**Comment by lucas-zimerman** [comment] 2021-09-23 17:05
Since you are not using transactions, for now, could you disable the DiagnosticSourceIntegration?

example:
```csharp
                    webBuilder.UseSentry(o =>
                    {
                        o.DisableDiagnosticSourceIntegration();
                    });
```

**Comment by STRATZ-Ken** [comment] 2021-09-23 17:15
![image](https://user-images.githubusercontent.com/24981405/134553572-445c8ee0-e2b8-41c5-9882-d1945bdfda9f.png)

Odd, am I missing something?

**Comment by lucas-zimerman** [comment] 2021-09-23 17:21
> ![image](https://user-images.githubusercontent.com/24981405/134553572-445c8ee0-e2b8-41c5-9882-d1945bdfda9f.png)
> 
> Odd, am I missing something?

It Could be missing the `using Sentry;` on the Program.cs

**Comment by STRATZ-Ken** [comment] 2021-09-23 17:26
@lucas-zimerman Yes, I didn't think it wouldnt auto define that include.  Testing now.

**Comment by STRATZ-Ken** [comment] 2021-09-23 17:33
This error still exists.  

```
2021-09-23 10:31:27.1708|ERROR|Sentry.ISentryClient|Failed to find BootTime: Now 9/23/2021 5:31:27 PM +00:00, GetTimestamp 44085901252128, Frequency 2246097, TicksPerSecond: 10000000|Attempted to divide by zero.|Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|DiagnosticLoggerExtensions.LogError => DiagnosticLoggerExtensions.LogIfEnabled => MelDiagnosticLogger.Log
2021-09-23 10:31:28.9953|ERROR|Sentry.ISentryClient|Failed to find BootTime: Now 9/23/2021 5:31:28 PM +00:00, GetTimestamp 44085905350507, Frequency 2246097, TicksPerSecond: 10000000|Attempted to divide by zero.|Sentry.Extensions.Logging.MelDiagnosticLogger.Log|48|DiagnosticLoggerExtensions.LogError => DiagnosticLoggerExtensions.LogIfEnabled => MelDiagnosticLogger.Log

```

However, I do not see the span errors anymore.  I do also want to mention that my API crashed last night with 

```
HTTP Error 503.2 - Service Unavailable
The serverRuntime@appConcurrentRequestLimit setting is being exceeded.
```

I have no evidence if this is caused by Sentry, but I wanted to mention as maybe you think that could be possible?

**Comment by lucas-zimerman** [comment] 2021-09-30 12:33
We'll look into what's going on with the BootTime error.
To speed up the analysis, would you mind describing the environment that your .NET application is running? (OS Windows/Linux,...) if running inside of Docker, ...

**Comment by STRATZ-Ken** [comment] 2021-09-30 12:37
- Windows 2012 R2 Fully Updated with IIS.
- .NET Core 5 w/ basic API server
No Docker or anything

**Comment by STRATZ-Ken** [comment] 2021-10-04 15:33
Is there a way to run this code via the NLog.config file as well?  I use some backend bots, and I just noticed NLog is reported the same span error in the internal nlog file.

Thanks,

**Comment by lucas-zimerman** [comment] 2021-10-04 20:17
In regard to the Divide by zero message, it seems to be an unexpected behavior on Windows Server 2012
https://github.com/getsentry/sentry-dotnet/issues/954

A way of avoiding the error in this case is to setup your SentryOptions with
`options.DetectStartupTime == StartupTimeDetectionMode.None`

The latter error in regard to spans will be fixed soon.

I am not entirely sure if it's possible to unload it directly on NLog.config, but disabling it on AddSentry should also work.

example here:
https://github.com/getsentry/sentry-dotnet/blob/58457e31a0490011afc4c2da9ac91604dfbf1ee3/samples/Sentry.Samples.NLog/Program.cs#L98-L149

In this case, you could add `o.DisableDiagnosticSourceIntegration();` inside of the Sentry Options callback:

```csharp
            var config = LogManager.Configuration = new LoggingConfiguration();
            _ = config
                .AddSentry(o =>
                {
                    o.DisableDiagnosticSourceIntegration();
...
```

**Comment by vermiceli** [comment] 2022-11-15 00:52
Has there been any movement on this issue? We recently updated from 3.10.0 to 3.23.1 and are seeing this error very frequently.  We did not see this warning in 3.10.0.  However, I believe that automatic instrumentation was enabled for us with 3.10.0.

If I disable the SQL instrumentation with `DisableDiagnosticSourceIntegration()`, the warning logs go away.  Is there something in the way we are using entity framework core or sqlclient that is causing this message?

**Comment by mattjohnsonpint** [comment] 2022-11-15 02:18
Hi @vermiceli - I think this one fell through the cracks.  Thanks for bringing it up again.   Can I please ask you to open a new issue so we can get fresh details?  I think there are a few different things being discussed above.

Thanks.

**Comment by mattjohnsonpint** [comment] 2022-11-19 03:29
Closing in favor of #2060. Thanks.

**Closed by mattjohnsonpint** 2022-11-19 03:29 UTC
Labels: bug, ASP.NET Core, Platform: .NET
