### ISSUE TITLE
There is no User information in Sentry when using ASP.NET Core

### ISSUE THREAD

**Issue by mmigala** [getsentry/sentry-dotnet#215] opened 2019-05-31 14:04 UTC
Hey guys,

I'm using Sentry version 1.2.0 with ASP.NET Core version 2.1. The only information I'm seeing about the user in Sentry is Ip ::1. This is the first time I'm using Sentry and I didn't try the previous versions.

https://stackoverflow.com/questions/56395494/sentry-doesnt-show-httpcontext-user-info-in-asp-net-core-application - I've posted on StackOveflow about the issue before I've posted here.

Below my current Sentry configuration
```
  "Sentry": {
    "Dsn": "",
    "IncludeRequestPayload": true,
    "SendDefaultPii": true,
    "MinimumBreadcrumbLevel": "Debug",
    "MinimumEventLevel": "Warning",
    "AttachStackTrace": true,
    "Debug": true,
    "DiagnosticsLevel": "Error"
  }
```

Regards

**Comment by bruno-garcia** [comment] 2019-05-31 14:25
Thanks for raising this. It would really speed things up if you could provide us with a link to a github repository where we can reproduce this issue.
Perhaps strip off your app to a bare mininum or create a small app which we can use to debug it.
Thanks!

**Comment by kanadaj** [comment] 2019-06-02 17:27
@mmigala have you tried setting the `sentryOptions.SendDefaultPii = true;` flag? without it, it might be just that it's stripping away the user info since it's PII.

**Comment by mmigala** [comment] 2019-06-04 07:42
@kanadaj 
Edited my post with current config

@bruno-garcia 
Will try to create a sample but it might take some time since I'm really swamped with work right now

**Comment by SimonCropp** [comment] 2021-12-16 10:36
@mmigala did you end up finding a solution for this problem?

**Comment by SimonCropp** [comment] 2021-12-28 11:38
closing this for age. if it still a problem please let us know and it would be helpful if you could include a full project that reproduces the issue

**Closed by SimonCropp** 2021-12-28 11:38 UTC
Labels: bug, ASP.NET Core, Platform: .NET
