### ISSUE TITLE
`3.30.0` fails to build with Unity 2019

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#2327] opened 2023-04-25 14:50 UTC
### Package

Sentry

### .NET Flavor

Mono

### .NET Version

2.0.0

### OS

Any (not platform specific)

### SDK Version

3.30.0

### Steps to Reproduce

Building in Unity 2019 with .NET SDK `3.30.0`. -> https://github.com/getsentry/sentry-unity/actions/runs/4770376708/jobs/8536361935

### Expected Result

Not breaking.

### Actual Result

```
  13:56:19.302 | Fatal error in Unity CIL Linker
  13:56:19.303 | Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task`1<System.IO.Stream> PolyfillExtensions::ReadAsStreamAsync(System.Net.Http.HttpContent,System.Threading.CancellationToken)' in assembly: 'Sentry.dll' ---> System.DllNotFoundException: libMonoPosixHelper.so
```

**Comment by mattjohnsonpint** [comment] 2023-04-25 18:11
I see the error here:  https://github.com/getsentry/sentry-unity/actions/runs/4770376708/jobs/8536361935#step:12:672 with longer stack trace:

```
13:54:18.144 | Fatal error in Unity CIL Linker
  13:54:18.144 | Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task`1<System.IO.Stream> PolyfillExtensions::ReadAsStreamAsync(System.Net.Http.HttpContent,System.Threading.CancellationToken)' in assembly: 'Sentry.dll' ---> System.DllNotFoundException: libMonoPosixHelper.so
  13:54:18.144 |   at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative.CreateZStream(System.IO.Compression.CompressionMode,bool,System.IO.Compression.DeflateStreamNative/UnmanagedReadOrWrite,intptr)
  13:54:18.145 |   at System.IO.Compression.DeflateStreamNative.Create (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean gzip) [0x0004a] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  13:54:18.145 |   at System.IO.Compression.DeflateStream..ctor (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean leaveOpen, System.Boolean gzip) [0x0002d] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  13:54:18.146 |   at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionMode mode, System.Boolean leaveOpen) [0x00000] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  13:54:18.146 |   at (wrapper remoting-invoke-with-check) System.IO.Compression.DeflateStream..ctor(System.IO.Stream,System.IO.Compression.CompressionMode,bool)
  13:54:18.146 |   at Mono.Cecil.MetadataReader.GetCustomDebugInformation (Mono.Cecil.Cil.ICustomDebugInformationProvider provider) [0x001b5] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.147 |   at Mono.Cecil.MetadataReader.GetDocument (System.UInt32 rid) [0x00012] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.147 |   at Mono.Cecil.MetadataReader.ReadSequencePoints (Mono.Cecil.MethodDefinition method) [0x0003f] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.148 |   at Mono.Cecil.Cil.PortablePdbReader.ReadSequencePoints (Mono.Cecil.Cil.MethodDebugInformation method_info) [0x00000] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.148 |   at Mono.Cecil.Cil.PortablePdbReader.Read (Mono.Cecil.MethodDefinition method) [0x00007] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.149 |   at Mono.Cecil.Cil.CodeReader.ReadMethodBody () [0x0006d] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.149 |   at Mono.Cecil.Cil.CodeReader.ReadMethodBody (Mono.Cecil.MethodDefinition method) [0x00014] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.150 |   at Mono.Cecil.MetadataReader.ReadMethodBody (Mono.Cecil.MethodDefinition method) [0x00000] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.150 |   at Mono.Cecil.MethodDefinition+<>c.<get_Body>b__41_0 (Mono.Cecil.MethodDefinition method, Mono.Cecil.MetadataReader reader) [0x00000] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.150 |   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet] (TRet& variable, TItem item, System.Func`3[T1,T2,TResult] read) [0x00040] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.151 |   at Mono.Cecil.MethodDefinition.get_Body () [0x0002c] in <421727e9882f4de49256484b6929de80>:0 
  13:54:18.151 |   at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x001c3] in <8f9f8e7cf41c4efab5970a6708c18c0e>:0 
  13:54:18.152 |   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x00041] in <bccba240[680](https://github.com/getsentry/sentry-unity/actions/runs/4770376708/jobs/8536361935#step:12:681)b40d3bf7a95d14758639a>:0 
  13:54:18.152 |   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x00021] in <8f9f8e7cf41c4efab5970a6708c18c0e>:0
```

Looks like the problem is somewhere with `DeflateStream`.  It just happens to be invoked when we read the stream from the HTTP response.

Searching a bit, it seems like this has happened before with Unity:
https://issuetracker.unity3d.com/issues/linux-dllnotfoundexception-error-when-using-deflatestream-if-there-is-no-libmonoposixhelper-dot-so-at-slash-usr-slash-lib

There's some recent comments there with a few other people saying it's happening yet again, so I think there's a regression on the Unity side for this.

A workaround would be to set `options.DecompressionMethods = DecompressionMethods.None` - but I'd hope we not have to resort to that.

At any rate, I think this is a Unity issue, not necessarily related specifically to sentry-dotnet 3.30.0.

**Comment by mattjohnsonpint** [comment] 2023-04-25 18:14
@bitsandfoxes - Does it _only_ appear when using `sentry-dotnet` 3.30.0?  Can you check if the same occurs for the previous release?  Though we changed some polyfills, we were still calling the same underlying methods previously.  It shouldn't have made any difference, AFAIK.

**Comment by mattjohnsonpint** [comment] 2023-04-30 01:51
Fixed by https://github.com/getsentry/sentry-unity/pull/1295

**Closed by mattjohnsonpint** 2023-04-30 01:51 UTC
Labels: bug, Platform: .NET
