### ISSUE TITLE
Xamarin.tvOS: MT5210: Native linking failed

### ISSUE THREAD

**Issue by dgyesbreghs** [getsentry/sentry-dotnet#847] opened 2021-02-16 08:22 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Sentry.Xamarin 1.0.2
Mono Runtime (Xamarin.TVOS)

### Steps to Reproduce

1. Install the Sentry.Xamarin NuGet
2. Setup the Sentry SDK.
3. Compile the application against a real device

### Expected Result

That the application would compile.

### Actual Result

The application did not compile. (See attached logs)
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5210: Native linking failed, undefined symbol: _ReadFile. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5202: Native linking failed. Please review the build log.
    3 Error(s)

**Comment by bruno-garcia** [comment] 2021-02-23 15:54
Could you please attach the logs too? What's tvOS version are you targeting?

The lowest targets the .NET SDK supports in .NET Standard 2.0 and .NET Framework 4.6.1.
Since tvOS isn't on the .NET Standard compat list:
![image](https://user-images.githubusercontent.com/1633368/108869557-4f0a1500-75c5-11eb-888c-783fffdddb60.png)

It might be that it simply isn't compatible with the Sentry SDK.

> No, even without the Xamarin package, we're still getting the error since package version 3.0.x.

This means you were able to use Sentry with Xamarin.tvOS when you used Sentry 2.x?

**Comment by dgyesbreghs** [comment] 2021-02-23 19:55
> Could you please attach the logs too? What's tvOS version are you targeting?
https://gist.github.com/dgyesbreghs/d38f3e6817eed9f1e4bd4d5e6284553a
> 
> The lowest targets the .NET SDK supports in .NET Standard 2.0 and .NET Framework 4.6.1.
> Since tvOS isn't on the .NET Standard compat list:
> ![image](https://user-images.githubusercontent.com/1633368/108869557-4f0a1500-75c5-11eb-888c-783fffdddb60.png)
> 
> It might be that it simply isn't compatible with the Sentry SDK.
Xamarin.iOS and Xamarin.tvOS is the same framework.
We're using Xamarin.iOS 14.10.0.4
> 
> > No, even without the Xamarin package, we're still getting the error since package version 3.0.x.
> 
> This means you were able to use Sentry with Xamarin.tvOS when you used Sentry 2.x?
Yes, we're currently using 2.x.

**Comment by bruno-garcia** [comment] 2021-02-23 20:11
Thanks for the logs and clarification.

I've tested an iOS app with `Sentry.Xamarin` (which is built on top of `Sentry 3.x`) and I could install it on my device.

Could you please share a repro so we can debug this?

**Comment by bruno-garcia** [comment] 2021-02-23 20:15
Oh: 

> 0>      wrapper_managed_to_native_Interop_Kernel32_ReadFile_System_Runtime_InteropServices_SafeHandle_byte__int_int__intptr in System.Reflection.Metadata.dll.o


This is probably about the stacktrace mode.
@dgyesbreghs can you try setting the stack trace mode to original?

https://docs.sentry.io/platforms/dotnet/configuration/options/#stack-trace-mode

**Comment by bruno-garcia** [comment] 2021-02-23 22:01
I tried Xamarin.iOS and was able to install `Sentry.Xamarin` 1.0.2 and run on a real device:

![image](https://user-images.githubusercontent.com/1633368/108913839-880fad00-75f8-11eb-99a9-f2a534567d66.png)

A repro would be helpful

**Comment by dgyesbreghs** [comment] 2021-02-24 17:47
Hi Bruno,

Below you can find the requested repo:
https://github.com/dgyesbreghs/sentry.demo

**Comment by bruno-garcia** [comment] 2021-02-26 03:25
Thanks for the repro! I was able to reproduce the error but I'm not exactly sure why it's failing to link. [I raised an issue in the Xamarin repository](https://github.com/xamarin/xamarin-macios/issues/10732) hopefully they have more insight on what's going on.

**Comment by bruno-garcia** [comment] 2021-02-27 00:39
I got a reply: https://github.com/xamarin/xamarin-macios/issues/10732#issuecomment-786521192

> The problem is that the `System.Reflection.Metadata.dll` has a P/Invoke to a function that doesn't exist on iOS (the Win32 function `ReadFile`):
> 
> ```
>      Undefined symbols for architecture arm64:
>        "_ReadFile", referenced from:
>            wrapper_managed_to_native_Interop_Kernel32_ReadFile_System_Runtime_InteropServices_SafeHandle_byte__int_int__intptr in System.Reflection.Metadata.dll.o
> ```
> 
> on iOS we usually require that assemblies only have P/Invokes to native functions that exists, because that allows us to create faster and smaller apps.
> 
> However, it's possible to turn this off for specific assemblies - in your case adding `--dlsym:System.Reflection.Metadata.dll` as an additional mtouch argument in the project's iOS Build options (for all device configurations) makes the sample app build successfully.
> 
> I'm closing this since it's the expected behavior in this scenario.

Could you try with `--dlsym:System.Reflection.Metadata.dll`?

I'm still wondering why this worked when I created a new project from scratch and deployed to my iOS device.

**Comment by dgyesbreghs** [comment] 2021-02-27 19:20
It's working with the extra mtouch argument. Thanks for the help.

**Comment by bruno-garcia** [comment] 2021-03-02 02:41
We need to add this to the docs then. Thanks for confirming.

**Comment by lucas-zimerman** [comment] 2021-10-06 18:12
Closing this since the above argument works with tvOS.
In addition, the topic about the Docs will be handled here: https://github.com/getsentry/sentry-xamarin/issues/59

**Closed by lucas-zimerman** 2021-10-06 18:12 UTC
Labels: documentation, tvOS
