### ISSUE TITLE
An error occurred when capturing the event `System.IO.FileLoadException`: Could not load file or assembly `'System.Reflection.Metadata, Version=5.0.0.0`

### ISSUE THREAD

**Issue by IhorKochetov** [getsentry/sentry-dotnet#1091] opened 2021-06-29 14:50 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Sentry 3.5.0 via Sentry.Serilog 3.5.0
.NET CORE 3.1.0, console app
Running in AWS ECS as dockerized task (UPD: is also reproducible locally as a simple ConsoleApp)

### Steps to Reproduce

1. Init logger on the start of the App (same SDK setup as in https://github.com/getsentry/sentry-dotnet/issues/1086)
2. Throw exception at the next line (`throw new ArgumentNullException("AppKey", "Was not found in EnvVars");`)

### Expected Result

Exception is captured and sent to sentry.io

### Actual Result

Exception is thrown internally in the SentryClient while trying to process the event. Debug logs are attached below:

```
2021-06-29T16:49:01.886+03:00	Debug: Logging enabled with ConsoleDiagnosticLogger and min level: Debug
2021-06-29T16:49:02.167+03:00	Debug: Using 'GzipBufferedRequestBodyHandler' body compression strategy with level Optimal.
2021-06-29T16:49:02.176+03:00	Debug: Initializing Hub for Dsn: 'https://3b7fa20d1e7c472d8ced22c0dafb02a3@o76841.ingest.sentry.io/5815988'.
2021-06-29T16:49:02.176+03:00	Debug: Registering integration: 'AppDomainUnhandledExceptionIntegration'.
2021-06-29T16:49:02.176+03:00	Debug: Registering integration: 'AppDomainProcessExitIntegration'.
2021-06-29T16:49:02.176+03:00	Debug: Registering integration: 'TaskUnobservedTaskExceptionIntegration'.
2021-06-29T16:49:02.267+03:00	Debug: New scope pushed.
2021-06-29T16:49:02.275+03:00	Info: Capturing event.
2021-06-29T16:49:02.280+03:00	Debug: Running processor on exception: Was not found in EnvVars (Parameter 'AppKey')
2021-06-29T16:49:02.297+03:00	Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
2021-06-29T16:49:02.382+03:00	Error: An error occurred when capturing the event System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
2021-06-29T16:49:02.382+03:00	File name: 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2021-06-29T16:49:02.382+03:00	at System.Diagnostics.Internal.PortablePdbReader..ctor()
2021-06-29T16:49:02.382+03:00	at System.Diagnostics.EnhancedStackTrace.GetFrames(StackTrace stackTrace) in /_/modules/Ben.Demystifier/src/Ben.Demystifier/EnhancedStackTrace.Frames.cs:line 74
2021-06-29T16:49:02.382+03:00	at Sentry.Extensibility.SentryStackTraceFactory.CreateFrames(StackTrace stackTrace, Boolean isCurrentStackTrace)+MoveNext() in /_/src/Sentry/Extensibility/SentryStackTraceFactory.cs:line 84
2021-06-29T16:49:02.382+03:00	at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
2021-06-29T16:49:02.382+03:00	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
2021-06-29T16:49:02.382+03:00	at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
2021-06-29T16:49:02.382+03:00	at Sentry.Extensibility.SentryStackTraceFactory.Create(StackTrace stackTrace, Boolean isCurrentStackTrace) in /_/src/Sentry/Extensibility/SentryStackTraceFactory.cs:line 67
2021-06-29T16:49:02.382+03:00	at Sentry.Extensibility.SentryStackTraceFactory.Create(Exception exception) in /_/src/Sentry/Extensibility/SentryStackTraceFactory.cs:line 40
2021-06-29T16:49:02.382+03:00	at Sentry.Internal.MainExceptionProcessor.CreateSentryException(Exception exception)+MoveNext() in /_/src/Sentry/Internal/MainExceptionProcessor.cs:line 113
2021-06-29T16:49:02.382+03:00	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2021-06-29T16:49:02.382+03:00	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2021-06-29T16:49:02.382+03:00	at Sentry.Internal.MainExceptionProcessor.Process(Exception exception, SentryEvent sentryEvent) in /_/src/Sentry/Internal/MainExceptionProcessor.cs:line 29
2021-06-29T16:49:02.382+03:00	at Sentry.SentryClient.DoSendEvent(SentryEvent event, Scope scope) in /_/src/Sentry/SentryClient.cs:line 209
2021-06-29T16:49:02.382+03:00	at Sentry.SentryClient.CaptureEvent(SentryEvent event, Scope scope) in /_/src/Sentry/SentryClient.cs:line 77
2021-06-29T16:49:02.382+03:00	.
2021-06-29T16:49:02.382+03:00	Info: Disposing the Hub.
2021-06-29T16:49:02.383+03:00	Debug: Disposing SentryClient.
2021-06-29T16:49:02.383+03:00	Debug: Disposing BackgroundWorker.
2021-06-29T16:49:02.384+03:00	Debug: Shutdown scheduled. Stopping by: 00:00:02. #0 in queue.
2021-06-29T16:49:02.384+03:00	Info: Exiting the worker with an empty queue.
2021-06-29T16:49:02.385+03:00	Debug: Disposing scope.
2021-06-29T16:49:02.385+03:00	Debug: Disposing SentryScopeManager.
2021-06-29T16:49:02.386+03:00	Unhandled exception. System.ArgumentNullException: Was not found in EnvVars (Parameter 'AppKey')
```

**Comment by bruno-garcia** [comment] 2021-06-29 15:05
Duplicate of #1050

@IhorKochetov we fixed this [in version 3.6.0](https://github.com/getsentry/sentry-dotnet/blob/main/CHANGELOG.md#360-alpha2).

Please upgrade to 3.6.0. On 3.5.0 the workaround is to add a dependency to: <PackageReference Include="System.Reflection.Metadata" Version="5.0.0" /> to your app directly

**Closed by bruno-garcia** 2021-06-29 15:05 UTC
