### ISSUE TITLE
Excessive Error Logs Obtaining Installation ID

### ISSUE THREAD

**Issue by vermiceli** [getsentry/sentry-dotnet#3526] opened 2024-08-07 20:00 UTC
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

Windows

### SDK Version

4.9.0

### Steps to Reproduce

1.  Load the application with Sentry enabled.
2.  Navigate to a page
3.  Observe error log `Failed to resolve persistent installation ID.`

Stack Trace
```
Access to the path 'C:\\[REDACTED]\\Sentry\\7AEC0D33F44D7BE1FE040D4A7C3045658D189EED' is denied.
System.UnauthorizedAccessException",
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Sentry.InstallationIdHelper.TryGetPersistentInstallationId()
```

### Expected Result

No error log message or just one until installation id is cached.  I believe this was introduced in [PR 3425](https://github.com/getsentry/sentry-dotnet/pull/3425/files). We just started seeing these when we upgrade from 4.5 to 4.9

Our logs are flooded with this message for every request, including static content like javascript files. I wouldn't think you'd need to check a file for every request and instead the id can be cached statically for all requests for a host process.

### Actual Result

An error log for every request to the web server

**Comment by jamescrosswell** [comment] 2024-08-12 02:28
Thanks for reporting this @vermiceli. It looks like a duplicate of https://github.com/getsentry/sentry-dotnet/issues/3524 - which I'm able to reproduce. I'll close this issue in favour of that one (which has a bit of discussion going already).

**Closed by jamescrosswell** 2024-08-12 02:28 UTC
Labels: Waiting for: Product Owner
