### ISSUE TITLE
Release Builds fail with 3.27.0 (ANRWatchDog$ANRListener is defined multiple times)

### ISSUE THREAD

**Issue by plequere-ms** [getsentry/sentry-dotnet#2153] opened 2023-02-03 06:35 UTC
### Package

Sentry

### .NET Flavor

Other

### .NET Version

7.0.0

### OS

Android

### SDK Version

3.27.0

### Steps to Reproduce

1. Install the latest Sentry for .net MAUI SDK (thru nuget)
2. Build Android app in RELEASE mode.
3. Observe build error (see below.)
4. Revert back to 3.26.2, rebuild, and the build succeeds.

### Expected Result

Build to complete

### Actual Result

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	JAVA0000	Error in obj\Release\net7.0-android\lp\191\jl\classes.jar:io/sentry/android/core/ANRWatchDog$ANRListener.class:
Type io.sentry.android.core.ANRWatchDog$ANRListener is defined multiple times: obj\Release\net7.0-android\lp\191\jl\classes.jar:io/sentry/android/core/ANRWatchDog$ANRListener.class, obj\Release\net7.0-android\lp\204\jl\classes.jar:io/sentry/android/core/ANRWatchDog$ANRListener.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Release\net7.0-android\lp\191\jl\classes.jar
io/sentry/android/core/ANRWatchDog$ANRListener.class
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
	at com.android.tools.r8.D8.main(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Release\net7.0-android\lp\191\jl\classes.jar:io/sentry/android/core/ANRWatchDog$ANRListener.class
	at Version.fakeStackEntry(Version_3.3.75.java:0)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:75)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:27)
	at com.android.tools.r8.internal.Fj.b(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:2)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:17)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:85)
	... 1 more
Caused by: com.android.tools.r8.internal.f: Type io.sentry.android.core.ANRWatchDog$ANRListener is defined multiple times: obj\Release\net7.0-android\lp\191\jl\classes.jar:io/sentry/android/core/ANRWatchDog$ANRListener.class, obj\Release\net7.0-android\lp\204\jl\classes.jar:io/sentry/android/core/ANRWatchDog$ANRListener.class
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:14)
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:33)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:6)
	at com.android.tools.r8.graph.B2$a.e(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:110)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:25)
	at com.android.tools.r8.D8.d(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:606)
	at com.android.tools.r8.D8.c(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:1)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:24)
	... 5 more
Directory 'obj\Release\net7.0-android\lp\191' is from 'sentry-android-core-6.10.0.aar'.	LoungeReviewMobileApp		1	

```

**Comment by mattjohnsonpint** [comment] 2023-02-03 06:40
Thanks for reporting, I'll investigate ASAP.

**Comment by mattjohnsonpint** [comment] 2023-02-03 06:54
This is cause by Xamarin-Android not cleaning up the generated java files in the `obj` folder, since some internal things changed between versions.  It is reproducible in both debug and release configurations, just by building once with the old version, then building again with the new.

You can fix it by either doing a "Rebuild" in VS, or with `dotnet build --no-incremental`, or by deleting the `obj` and `bin` folders before starting the build.  You should only need to do this once.

Closing this, but LMK if it works or not, and I'll re-open if necessary.  Thanks!

**Closed by mattjohnsonpint** 2023-02-03 06:54 UTC
Labels: bug, Platform: .NET, Android

**Comment by plequere-ms** [comment] 2023-02-03 07:04
Thank you for the incredibly quick response.

Rebuild is the first thing I tried when I hit the issue but it didn't work for me. But deleting the bin and obj folders did the trick indeed. Thanks again!
