### ISSUE TITLE
DB Connection spans are not being finished

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2372] opened 2023-05-16 21:34 UTC
### SDK Version

3.31.0

### Steps to Reproduce

ASP.NET Core 7 with EF Core 7.

In a controller action, make a database call, then an HTTP call.  Wrap each in their own span.

- Start Span 1
- Query Database
- Finish Span 1

- Start Span 2
- Make API call
- Finish Span 2

### Expected Result

Span 1 and Span 2 should be siblings, one following the next.

### Actual Result

Span 2 is nested within the `db.connection` of Span 1, because the span was not closed.

![image](https://github.com/getsentry/sentry-dotnet/assets/1396388/8ec47813-8230-4789-8aef-471d1682bb44)

The `db.connection` span status is `deadline_exceeded`.  In other words, it wasn't finished when the query was done with the connection, but rather it was still open when the transaction was finished.

**Comment by mattjohnsonpint** [comment] 2023-05-16 21:36
A workaround:  Manually finish the connection span after the query is done.

```csharp
var span = SentrySdk.GetSpan();
if (span?.Operation == "db.connection")
{
    span.Finish();
}
```

Gives the desired result:

![image](https://github.com/getsentry/sentry-dotnet/assets/1396388/6f703c55-2866-40c4-9267-f6a00b70caa1)

But this shouldn't be necessary.

**Comment by mattjohnsonpint** [comment] 2023-05-16 21:36
Related to #2144 - which is slightly different in presentation but also related to `db.connection` spans.

**Comment by jamescrosswell** [comment] 2023-05-24 02:06
I'm unable to reproduce this... using ASP.NET Core 7 and EF Core 7. I am using Postgres rather than MS SQL (can't imagine that's relevant to Sentry).

This is the Sentry configuration I used:

```
// Configure Sentry
builder.WebHost.UseSentry(options =>
{
    options.Dsn = "[Redacted]";
    options.EnableTracing = true;
    options.TracesSampleRate = 1.0;
});

builder.Services.AddHttpClient();
```

This is the controller action I wired up:

```
    public IActionResult Index([FromServices] IHub sentry)
    {
        var model = new HomeViewModel();

        ITransaction? transaction = null;
        try
        {
            transaction = sentry.StartTransaction("home", "get-index");
            
            // Start Span 1
            ISpan? dbSpan = null;
            try
            {
                dbSpan = transaction.StartChild("db query", "getting a list of customer");
        
                var query = _context.Customers.OrderBy(c => c.LastName).ThenBy(c => c.FirstName).Take(10);
                model.Customers = query.ToList();
            }
            finally
            {
                // Finish Span 1
                dbSpan?.Finish();
            }

            // Start Span 2
            ISpan? httpSpan = null;
            try
            {
                httpSpan = transaction.StartChild("http", "GET https://www.google.com");
                
                var httpClient = _httpClientFactory.CreateClient();
                var request = new HttpRequestMessage(HttpMethod.Get, "https://www.google.com");
                var response = httpClient.Send(request);
                model.StatusCode = response.StatusCode;
            }
            finally
            {
                // Finish Span 2
                httpSpan?.Finish();
            }
        }
        finally
        {
            transaction?.Finish();
        }
        
        return View(model);
    }
```

This is [how it looks in the performance dashboard](https://sentry-sdks.sentry.io/performance/aspnet-core:9c5bb2e054834fe7a127bc7ddad0065a/) in Sentry.

**Comment by jamescrosswell** [comment] 2023-05-25 00:05
I was able to reproduce this. The code in my controller action looks like:

```csharp
    public async Task<IActionResult> Index([FromServices] IHub sentry)
        var query = _context.Customers.OrderBy(c => c.LastName).ThenBy(c => c.FirstName).Take(10);
        var customers = await query.ToListAsync();
        
        var httpClient = _httpClientFactory.CreateClient();
        var request = new HttpRequestMessage(HttpMethod.Get, "https://www.google.com");
        var response = await httpClient.SendAsync(request);
        var statusCode = response.StatusCode;
    
        var model = new HomeViewModel
        {
            Customers = customers,
            StatusCode = statusCode
        };
        return View(model);
    }
```

I added a bit of logging to the console in our diagnostics listener `SentryEFCoreListener.OnNext` to check if we were even getting sufficient information from the diagnostics stream to be able to identify when the db connection is finishing and indeed we are:

```
Microsoft.EntityFrameworkCore.Infrastructure.ContextInitialized (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Connection.ConnectionCreating (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Connection.ConnectionCreated (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Command.CommandCreating (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Command.CommandCreated (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Command.CommandInitialized (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpening 
    (Sentry add span db.connection)
Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpened (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting 
    (Sentry add span db.query)
Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted 
    (Sentry take span db.query)
Microsoft.EntityFrameworkCore.Database.Command.DataReaderClosing (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Command.DataReaderDisposing (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Connection.ConnectionClosing (Sentry ignored)
Microsoft.EntityFrameworkCore.Database.Connection.ConnectionClosed 
    (Sentry take span db.connection)
```

Digging in further, the TakeSpan that gets triggered above when the connection gets closed is unable to retrieve the original span representing the DB connection. The logs say it's already been garbage collected... which is odd. 

I added a bit more detailed logging to get some visibility of what's going on with the spans in our TransactionTracer and the span we're after is definitely still there... but for some reason we've lost our weak reference to it and so our code assumes it's been garbage collected.

```
******************************
* With more detailed logging *
******************************

Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpening (Sentry add span db.connection)
Transaction Spans
-----------------

Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting (Sentry add span db.query)
Transaction Spans
-----------------
id: 02c2f5e4765f4b06 operation: db.connection 

Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted (Sentry take span db.query)
Transaction Spans
-----------------
id: 181bfe37269347f8 operation: db.query 
id: 02c2f5e4765f4b06 operation: db.connection  

Microsoft.EntityFrameworkCore.Database.Connection.ConnectionClosing (Sentry take span db.connection)
Transaction Spans
-----------------
id: 181bfe37269347f8 operation: db.query
id: 02c2f5e4765f4b06 operation: db.connection description: 
TakeSpan failed - span already garbage collected
```

Now I just have to work out why we're losing the `WeakReference`. About the only hypothesis I've got at the moment is that potentially the span is being recreated by a filter or something somewhere... so although it's still sitting on the TransactionTracer, potentially it's a different instance/reference that looks the same but ain't.

**Comment by jamescrosswell** [comment] 2023-05-25 04:36
One more clue... 

Sentry uses AsyncLocal to store weak references to the various spans and you can pass a value change handler into the constructor of an AsyncLocal to be informed when the value changes... which I did and then I generated some more logs!

```
***************************
* Logging Warp Factor 9 ! *
***************************

Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpening (Sentry add span db.connection)
(Sentry add span db.connection)
Transaction Spans
-----------------
_spansConnectionLocal changed from null to cb48ca0d4a994760


Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpened (Sentry ignored)
_spansConnectionLocal changed from cb48ca0d4a994760 to null


Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting (Sentry add span db.query)
(Sentry add span db.query)
Transaction Spans
-----------------
id: cb48ca0d4a994760 operation: db.connection
_spansQueryLocal changed from null to 0ffa7ee5a78c4cef
_spansQueryLocal changed from 0ffa7ee5a78c4cef to null
_spansQueryLocal changed from null to 0ffa7ee5a78c4cef
_spansQueryLocal changed from 0ffa7ee5a78c4cef to null
_spansQueryLocal changed from null to 0ffa7ee5a78c4cef

Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted (Sentry take span db.query)
(Sentry take span db.query)
Transaction Spans
-----------------
id: 0ffa7ee5a78c4cef operation: db.query
id: cb48ca0d4a994760 operation: db.connection
originalSpan: db.query
_spansQueryLocal changed from 0ffa7ee5a78c4cef to null


Microsoft.EntityFrameworkCore.Database.Command.DataReaderClosing (Sentry ignored)
dbug: 25/05/2023 16:04:31.247 RelationalEventId.DataReaderClosing[20301] (Microsoft.EntityFrameworkCore.Database.Command) 
      Closing data reader to 'dvdrental' on server 'tcp://localhost:5432'.
Microsoft.EntityFrameworkCore.Database.Command.DataReaderDisposing (Sentry ignored)
dbug: 25/05/2023 16:04:31.247 RelationalEventId.DataReaderDisposing[20300] (Microsoft.EntityFrameworkCore.Database.Command) 
      A data reader for 'dvdrental' on server 'tcp://localhost:5432' is being disposed after spending 0ms reading results.


Microsoft.EntityFrameworkCore.Database.Connection.ConnectionClosing (Sentry take span db.connection)
(Sentry take span db.connection)
Transaction Spans
-----------------
id: 0ffa7ee5a78c4cef operation: db.query
id: cb48ca0d4a994760 operation: db.connection
originalSpan: null
TakeSpan failed - span already garbage collected
```

So...

1. When Sentry receives the `Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpening` diagnostic event we add a span for the db.connection and assign this to our `AsyncLocal<WeakReference<ISpan>> _spansConnectionLocal`. 
2. The next diagnostic event Sentry receives from EF is: `Microsoft.EntityFrameworkCore.Database.Connection.ConnectionOpened` (which Sentry ignores... it's tracking time from the connection opening event above, which makes sense - end to end timing)
3. Immediately after that however, `_spansConnectionLocal` is being reset to `null`

How and why is a mystery though. The Span being referenced by the WeakReference hasn't been garbage collected. This is an AsyncLocal (not a ThreadLocal) so it shouldn't be influenced by other threads at all and there are no clues in the call stack, that I can see.

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/fd4d298e-9e8d-45a8-a278-a92a1f079c92)

**Comment by jamescrosswell** [comment] 2023-05-25 08:38
@mattjohnsonpint the way `SentryEFCoreListener` is currently implemented, leverages three variables:

```csharp
    private readonly AsyncLocal<WeakReference<ISpan>> _spansCompilerLocal = new();
    private readonly AsyncLocal<WeakReference<ISpan>> _spansQueryLocal = new();
    private readonly AsyncLocal<WeakReference<ISpan>> _spansConnectionLocal = new();
```

When `SentryEFCoreListener` receives an `EFConnectionOpening` a span is created and a weak reference stored in `_spansConnectionLocal`. Later, when `EFConnectionClosed` is received, we try to retrieve the weak reference and call `Span.Finish()`.

Similarly the `EFCommandExecuting` and `EFCommandExecuted` diagnostic messages are used to create and finish a Span for queries, storing a temporary reference in `_spansQueryLocal`. 

I think this will only work in the simplest of scenarios, however... it assumes that there will only ever be one query running concurrently, for example. If ever we have two queries running concurrently, we'll lose the weak reference to the Span representing at least one of those queries... and that Span will never be finished. 

Is there some deeper magic going on here that I don't understand yet, or does this code need a bit of love?

**Closed** 2023-06-07 21:57 UTC
Labels: bug, Impact: Medium, Effort: Medium, Platform: .NET
