### ISSUE TITLE
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper'

### ISSUE THREAD

**Issue by CCC598** [getsentry/sentry-dotnet#307] opened 2019-11-12 09:57 UTC
- [ ] ASP.NET Core 3.0
- [ ] .NET Core 3.0
- [ ] Sentry.AspNetCore 1.2.0

In ASP.NET Core 3.0:
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT1.ProcessRequestAsync()

I look source code, this class is internal. 
https://source.dot.net/#Microsoft.AspNetCore.Http/Internal/BufferingHelper.cs

**Comment by bruno-garcia** [comment] 2019-11-12 16:49
Please use the `2.0.0-beta6`, it's fixed there.

It's not `2.0.0` yet because we'll fit a few more "breaking changes" into it, which unlikely will affect you, and if it does, the compiler would tell you.

**Comment by bruno-garcia** [comment] 2019-11-15 04:08
I'll close this since it's a dupe of #249 and it's fixed in the latest beta

**Closed by bruno-garcia** 2019-11-15 04:08 UTC
