### ISSUE TITLE
Stacktrace not available with OWIN and .NET Framework 4.6.1

### ISSUE THREAD

**Issue by lfongaroScp** [getsentry/sentry-dotnet#283] opened 2019-10-08 08:50 UTC
Hi,

I integrate sentry in my project (target is .NET Framework 4.6.1) with OWIN
I follow this example to integrate sentry with my project
https://github.com/getsentry/sentry-dotnet-samples/tree/master/AspNetOwinWebApi

In the dashboard I see the exceptions throw in the code, but they have not a stacktrace or there is only the row that throw the exception without any other information.

In another project (with net core 2.2) I do not have this problem.

**Comment by bruno-garcia** [comment] 2019-10-08 11:27
That's odd. In the sample project you've linked, there's a screenshot which includes stacktrace.
Could you please share some repro so we can investigate?

**Comment by bruno-garcia** [comment] 2020-02-06 18:19
I'm closing this because can't reproduce.
Stack traces are working with OWIN since this is added by the base Sentry package. Just make sure to have pdb's available.
Feel free to reopen if the issue continues.

**Closed by bruno-garcia** 2020-02-06 18:19 UTC
Labels: .NET Framework, OWIN
