### ISSUE TITLE
ApplicationVersionLocator returns null in some instances

### ISSUE THREAD

**Issue by xt0rted** [getsentry/sentry-dotnet#53] opened 2018-07-17 18:54 UTC
The method of getting the executing assembly, `Assembly.GetEntryAssembly()`, can return null when the assembly is [loaded from unmanaged code](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.getentryassembly(v=vs.110).aspx#Anchor_1). In my case it's because I'm running this in an MVC5 & .NET 4.7.1 website where IIS ends up loading the site's dll and executing it.

I don't think there's any way to get this to work automagically, so setting the `Release` manually is the only option in this type of setup.

If this library is intended to be run in classic asp.net websites then a note about this might be nice in the docs.

**Comment by bruno-garcia** [comment] 2018-10-24 10:35
@xt0rted I'll close this as this is by design.
The automatic assembly version locator is not going to work on ASP.NET Classic with IIS.

**Closed by bruno-garcia** 2018-10-24 10:35 UTC
Labels: question
