### ISSUE TITLE
4.5 Upgrading 4.6.1

### ISSUE THREAD

**Issue by xml1234** [getsentry/sentry-dotnet#2584] opened 2023-08-29 11:12 UTC
### Problem Statement

Hello, I have created a new project with a target framework of 4.5, but after upgrading to 4.6.1, I cannot use it. It is a brand new project and I have not done anything

**Comment by bitsandfoxes** [comment] 2023-08-29 11:19
Hey there. Do you have anything for us to go on? An error message, logs etc.?

**Comment by xml1234** [comment] 2023-08-30 00:57
Hello, there are no exceptions generated in the system. SentryId has a return value

**Comment by jamescrosswell** [comment] 2023-08-30 03:02
@xml1234 would it be possible to share a minimal reproducable example of the problem (e.g. as a GitHub project)?

**Comment by xml1234** [comment] 2023-08-30 03:39
I have only added these few lines of code, and I will share them below. Sorry, I cannot upload the code because the network here does not allow

**Comment by xml1234** [comment] 2023-08-30 03:39
protected void Application_Start()
        {

            #region Sentry
            // Initialize Sentry to capture AppDomain unhandled exceptions and more.
            SentrySdk.Init(o =>
            {
                o.AddAspNet();
                o.Dsn = "";
                // When configuring for the first time, to see what the SDK is doing:
                o.Debug = true;

                // Example sample rate for your transactions: captures 10% of transactions
                o.TracesSampleRate = 1.0;

                // If you also installed the Sentry.EntityFramework package
                o.AddEntityFramework();
            });
            #endregion


            try
            {
                throw new Exception("this is error");
            }
            catch (Exception err)
            {
                SentryId sentryId = SentrySdk.CaptureException(err);
            }


            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

        }

**Comment by jamescrosswell** [comment] 2023-08-31 03:41
@xml1234 are you using the latest version of Sentry (3.36.0)?

**Comment by xml1234** [comment] 2023-08-31 03:58
@jamescrosswell No, I'm using 3.34.0

**Comment by xml1234** [comment] 2023-08-31 04:06
The same goes for (3.36.0)

**Comment by jamescrosswell** [comment] 2023-08-31 08:26
So I just tried to do this myself and, from the code you provide at least, it looks like you're missing quite a bit of the setup in your  `HttpApplication` class. Take a look at the [Guide for ASP.NET](https://docs.sentry.io/platforms/dotnet/guides/aspnet/) - it has all this stuff in there as well:

```csharp
    // Global error catcher
    protected void Application_Error() => Server.CaptureLastError();

    protected void Application_BeginRequest()
    {
        Context.StartSentryTransaction();
    }

    protected void Application_EndRequest()
    {
        Context.FinishSentryTransaction();
    }

    protected void Application_End()
    {
        // Flushes out events before shutting down.
        _sentry?.Dispose();
    }
```

Let me know if that helps.

**Comment by xml1234** [comment] 2023-08-31 08:31
@jamescrosswell I added these, but they didn't have any effect

**Comment by jamescrosswell** [comment] 2023-08-31 11:08
OK thanks @xml1234 ... I'm not able to reproduce any problems here. If there's any way you can provide a demo project that reproduces the problem, I can look into it further... otherwise it's hard to guess what might be going on.

**Comment by bitsandfoxes** [comment] 2023-09-08 14:53
Closing this. There doesn't seem to be anything we can do right now.
Please feel free to reopen this issue with a repro.

**Closed by bitsandfoxes** 2023-09-08 14:53 UTC
Labels: enhancement, Platform: .NET
