### ISSUE TITLE
Cannot read input zip file because of Sentry IncludeRequestPayload is activated

### ISSUE THREAD

**Issue by madmox** [getsentry/sentry-dotnet#175] opened 2019-03-22 09:14 UTC
We have an API controller with the following action:

```csharp
public async Task<IActionResult> UnpackZipFile()
{
    try
    {
        using (var zip = new ZipArchive(this.Request.Body))
        {
            // Process ZIP file
        }
        return new OkResult();
    }
    catch (Exception ex)
    {
        this._logger.LogError(ex, "Could not unpack zip file");
        return new BadRequestResult();
    }
}
```

When Sentry's `IncludeRequestPayload` is `false`, the action behaves correctly. `this.Request.Body` is of type `Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream` in this case.

When Sentry's `IncludeRequestPayload` is `true`, the using part throws a `System.NotSupportedException` exception, with the message "The content has not been fully buffered yet". This time `this.Request.Body` is of type `Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream`. Moreover, if the file is too large the log is not even sent to Sentry!

I suspect the Sentry middleware to wrap the request body stream in a rewindable `FileBufferingReadStream`, but this stream is incompatible with the `ZipArchive` constructor. I have no clue whether I'm doing something wrong in my original code, or if this is a bug the Sentry team should fix.

I am using ASP.NET Core 2.2 with **IIS in-process hosting model** and Sentry.AspNetCore NuGet in version 1.1.2.

**Comment by madmox** [comment] 2019-03-22 09:48
Additional info: if you log an event *before* the using statement, the API action succeeds but the event never shows up in Sentry.

I think in this case the logging instruction fully buffers the `FileBufferingReadStream` to prepare the event data, but fails to send it to sentry because of the file size. But when the using statement is executed it works because the stream is fully buffered (and seeked to origin).

**Comment by bruno-garcia** [comment] 2019-03-22 10:34
@madmox Thanks for reporting this. Sounds like something we should take a look and address.
Do you happen to have a repro we can debug through?
Perhaps we would only `EnableRewind` on the request if the `Stream` type is known and supported (white-listing).

With regards to the size of the request/dropping the event we have a PR WIP which will address it:
https://github.com/getsentry/sentry-dotnet/pull/174

**Comment by madmox** [comment] 2019-03-22 11:13
I'm not sure it's possible for the Sentry middleware to check the input stream type without wrapping it in a `FileBufferingReadStream`. Perhaps by checking the request's `Content-Type` header (and maybe `Content-Length`) before doing anything on the body stream. But then you also want a configurable white list of additional supported content types to allow client implementations to register their own custom text-based content types.

I don't have a repo to point you at right now, maybe I can do that sometime in the next few days.

**Comment by madmox** [comment] 2019-04-01 15:37
I created [a sample repo](https://github.com/madmox/Sentry.DemoProject) to reproduce the issue. It's configured to run under dotnet core 2.2 though, so you might wanna install it before testing (it's not included with VS 2017).

**Comment by bruno-garcia** [comment] 2019-05-02 15:03
@madmox Thanks for the repro! I was able to simulate the error when enabling the buffering of requests.

As it turns out, the issue is not related to the Sentry SDK directly. Yes it is the SDK that enables request buffering with `EnableRewind` but that might as well be done by another framework feature or package. 

The SDK doesn't _do_ anything with the request before it hits your controller. It only calls `EnableRewind` to be able to `Seek(Begin)` *only in case there's an exception*.

The issue is actually with [FileBufferingReadStream Seek](https://github.com/aspnet/AspNetCore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/WebUtilities/src/FileBufferingReadStream.cs#L171) which will throw if you try to Seek the end of the stream when the underlying Stream has not being read yet in combination with [ZipArchive](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs#L525) which starts reading the stream from the end.

I assume they chose to throw here because the alternative would be to block the thread while buffering.

One way to work around this is simply consuming the `Body` stream before passing it to `ZipArchive`.

Would be great if `FileBufferingReadStream` had some API like:
`await Request.Body.BufferAsync();` where you can await asynchronously for it to read the whole request but there's no such API. Again, maybe because there's no nice way to make one.

Some work around could look like (which is inefficiently duplicating all data over to a `MemoryStream`):

```csharp
using (var mem = new MemoryStream())
{
    await this.Request.Body.CopyToAsync(mem);
    using (var zip = new ZipArchive(mem)) // Won't throw anymore
    {
        entriesCount = zip.Entries.Count;
    }
}
```

Or just reading it into some small throw-away buffer. The data is anyway buffered in the `FileBufferingReadStream`. Still wasted copying and allocations (`Task`) going on though:

```csharp
var buffer = new byte[1024]; // magic buffer size
var re = 0;
do
{
    re = await this.Request.Body.ReadAsync(buffer, 0, buffer.Length);
} while (re > 0);
this.Request.Body.Position = 0;
// Free to use this.Request.Body now with ZipArchive
```

Lets call those _work arounds_ for now as it seems the ideal solution here is offering an API in the Sentry SDK to avoid enabling request body rewinding altogether. But instead of whitelisting a user-defined `Content-Type` list, we can go with a single callback that gets invoked in the `SentryMiddleware` before calling `EnableRewind` giving your the whole Request, or something else. Needs some discussion I guess.

Important to note that this issue will end up hitting more people, unrelated to Sentry's SDK.

**Comment by bruno-garcia** [comment] 2019-06-03 21:15
@madmox could you please review #200 and give some feedback?
We'd be merging this to address your issue unless you've found some other workaround.

**Comment by bruno-garcia** [comment] 2020-09-11 20:01
This was resolved with the option `MaxRequestBodySize`:

https://github.com/getsentry/sentry-dotnet/blob/1ab7c273d569b356c2f32a0d16fac9749275507e/src/Sentry.AspNetCore/SentryMiddleware.cs#L89-L92

**Closed by bruno-garcia** 2020-09-11 20:01 UTC
Labels: ASP.NET Core, bug
