### ISSUE TITLE
Serious system performance degradation on upgrading to this from RavenSdk

### ISSUE THREAD

**Issue by jrwpatterson** [getsentry/sentry-dotnet#479] opened 2020-08-11 05:20 UTC
Please mark the type framework used:

- [ ] ASP.NET MVC
- [x] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [x] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version: 4.8

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.15

We upgraded our sentry client from RavenSDK to this. On doing so our entire systems suffered significant degradation where we reduced server throughput. We also saw several servers becoming non-responsive at random. There were no logs in either the application logs, windows logs, dynatrace, or sentry that would give us an indication of what the issue was. 

After we disabled the sentry client our system has returned to normal but we are now blind from errors.

**Comment by snakefoot** [comment] 2020-08-11 19:09
Sounds like a duplicate of #384 

I'm guessing it is because the Sentry-client always captures complete StackTrace for each LogEvent, when not including an Exception-object. This gives a huge penalty for the application-thread logging.

**Comment by bruno-garcia** [comment] 2020-08-18 13:48
@snakefoot to capture the stacktrace for non exception you must opt-in with the option `attachStacktrace`.
By default it doesn't do that. Have you suffered some perf degradation without this feature too?

**Comment by bruno-garcia** [comment] 2020-09-11 19:23
@snakefoot can you confirm you're using `attachStacktrace`? And how does it perform if you remove this option?

**Comment by snakefoot** [comment] 2020-09-12 08:16
@bruno-garcia Think you should ask @jrwpatterson whether using `attachStacktrace`? And how does it perform if removing this option?

**Comment by bruno-garcia** [comment] 2020-09-15 04:18
Yes, sorry, wrong @

**Comment by bruno-garcia** [comment] 2021-01-04 02:02
I'll close this as if you have this SDK in a tight loop (with default values) generating events it'll consume a lot less resources than SharpRaven.

Feel free to reopen if you have some repro, or an update about `attackStacktrace=true`.

**Closed by bruno-garcia** 2021-01-04 02:02 UTC
Labels: question
