### ISSUE TITLE
`SentrySdk.GetSpan` always returns null

### ISSUE THREAD

**Issue by michaelmairegger** [getsentry/sentry-dotnet#975] opened 2021-05-11 09:05 UTC
Which SDK and version?
- WPF .NET5
- Xamarin.Forms netstandard2.0

### Steps to Reproduce

    var span = SentrySdk.GetSpan() ?? SentrySdk.StartTransaction("tx", "tx");
    var span1 = span.StartChild("child");
    var span2 = SentrySdk.GetSpan();

### Expected Result

Get latest span

### Actual Result

`span2` is null? Shouldn't it be equal to span1? Or am I misunderstanding something?

I have tried the same code with a surrounding:

    using(var scope = SentrySdk.PushScope())
    {
         ..
    }

**Comment by bruno-garcia** [comment] 2021-05-11 23:36
Turns out this is undocumented, but you need to bind the transaction to the scope if you want `SentrySdk.GetSpan` to return something.

`StartSpan` and `StartTransaction` don't have side effect. It's not keeping a reference under the hood so you need to:
```
SentrySdk.ConfigureScope(s => s.Transaction = transaction);
```

Now `SentrySdk.GetSpan()` is able to find that.

We definitely need to document this.

**Comment by michaelmairegger** [comment] 2021-05-13 07:28
@bruno-garcia Ok, thanks I will try that.

Yes, I am useing the SDK for Xamarin.Form and the one for WPF

**Comment by Tyrrrz** [comment] 2021-05-24 18:49
@bruno-garcia 

> We definitely need to document this.

Should this be a higher level documentation issue (i.e. on `sentry-docs`) or is it something we should address locally?

**Comment by bruno-garcia** [comment] 2021-05-24 19:38
@Tyrrrz The JS docs always showed that the user must add to the scope: https://docs.sentry.io/platforms/javascript/performance/instrumentation/custom-instrumentation/

At this point I think best we just do the same. What do you think?

**Comment by Tyrrrz** [comment] 2021-05-24 19:56
Yeah sounds reasonable. Can we move the issue to `sentry-docs` then?

**Comment by bruno-garcia** [comment] 2021-05-31 21:26
The problem is that if I move it there I can't assign this to you. Can we keep this one here and the PR there instead?

**Comment by Tyrrrz** [comment] 2021-05-31 22:10
ok

**Closed as completed** 2021-10-06 18:42 UTC
Labels: Documentation
