### ISSUE TITLE
Custom tag doesn't work with PushProperty

### ISSUE THREAD

**Issue by hookenful** [getsentry/sentry-dotnet#1653] opened 2022-05-11 12:10 UTC
### Package

Sentry.Serilog

### .NET Flavor

.NET

### .NET Version

6.0.1

### OS

macOS

### SDK Version

6.0.1

### Steps to Reproduce

Hello there!

I am trying to enrich logs with CorrelationId property, I have such middleware where, I am generating and pushing property to Serilog `LogContext`

```
public class LogContextMiddleware : IMiddleware
{
    private readonly ICorrelationIdFactory _correlationIdFactory;

    public LogContextMiddleware(ICorrelationIdFactory correlationIdFactory)
    {
        _correlationIdFactory = correlationIdFactory;
    }

    public async Task InvokeAsync(HttpContext context, RequestDelegate next)
    {
        var correlationId = _correlationIdFactory.Create();
        using(LogContext.PushProperty("CorrelationId", correlationId))
        {
            await next(context);
        }
    }
}
```

And I have Sentry that setup in Serilog:
```
 .WriteTo.Sentry(o =>
        {
            o.MinimumBreadcrumbLevel = LogEventLevel.Information; 
            o.MinimumEventLevel = LogEventLevel.Error; 
            o.Dsn = "<dsn url>";
            o.AttachStacktrace = true;
            o.TextFormatter = new MessageTemplateTextFormatter("[{CorrelationId}] {Message}", null);
        });
```

But I am not seeing CorrelationId in any tags neither in tags section in Sentry UI nor in message formatted text output. Just empty [] here.

What did I miss in configuration? Thanks in advance!

### Expected Result

1. Persistence of CorrelationId in tags section, available for search 
2. Formatted text specified in MessageTemplateTextFormatter

### Actual Result

**Tag section:**

![image](https://user-images.githubusercontent.com/31849464/167846084-135df3cc-8041-4518-b2e6-04f77e613627.png)

**Formatted message:**

MESSAGE
[] Failed to create identity user for "testuser@me.com" because '"Token is empty"'

**Comment by hookenful** [comment] 2022-05-17 05:51
Any help on that?

**Comment by SimonCropp** [comment] 2022-05-26 04:17
i put together a small repro. https://github.com/SimonCropp/SentryAspCoreSerilogRepro not it is pointing to my dsn

and it seems to work for me 

![image](https://user-images.githubusercontent.com/122666/170414722-227a1448-17b5-4743-95bb-e8bd407ed6c6.png)

I have invited you as a collaborator.  would you be able to modify in such a way as to illustrate the bug you are experiencing

**Comment by mattjohnsonpint** [comment] 2022-05-26 22:15
@hookenful - We'll keep this open for a while so you can experiment with Simon's repro.  Let us know how it goes please.

Thanks!

**Comment by SimonCropp** [comment] 2022-07-28 10:34
@hookenful will close this one for now since we cant repro. let me if you can help with modifying https://github.com/SimonCropp/SentryAspCoreSerilogRepro/blob/main/Program.cs to reproduce your scenario

**Closed by SimonCropp** 2022-07-28 10:34 UTC
Labels: bug, Platform: .NET
