### ISSUE TITLE
use ocelot api gateway

### ISSUE THREAD

**Issue by EngRajabi** [getsentry/sentry-dotnet#276] opened 2019-09-22 06:54 UTC
https://github.com/ThreeMammals/Ocelot/issues/1021

**Comment by bruno-garcia** [comment] 2019-09-22 13:30
@EngRajabi Could you please elaborate?
What's the expected vs actual behavior? How can we reproduce the issue?

**Comment by EngRajabi** [comment] 2019-09-23 11:46
If using the use sentry command, use the ocelot project next to it. You have trouble.
There is a problem with your post method. If so, the api gateway, which is ocelot, cannot properly call services and the content type will not be sent

**Comment by serjebulavsky** [comment] 2019-10-10 07:44
@EngRajabi it is an issue of Ocelot (https://github.com/ThreeMammals/Ocelot/issues/792), you can change sentry's Max Request Body Size to none, so sentry won't turn on request body buffering, with which Ocelot conflicts. 

@bruno-garcia you can setup Ocelot simple service, and include Sentry there. Because option MaxRequestBodySize in sentry options triggers request body buffering, somehow ocelot doesn't like that and cuts body of the requests.

**Comment by bruno-garcia** [comment] 2020-07-31 17:47
Dupe of #387

**Closed by bruno-garcia** 2020-07-31 17:47 UTC
Labels: question
