### ISSUE TITLE
`ObjectDisposedException` in `BackgroundWorker` when used with Serilog on AWS Lambda

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#1086] opened 2021-06-24 11:23 UTC
Project:

```xml
<Project Sdk="http://Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Sentry" Version="3.5.0" />
        <!-- <PackageReference Include="Sentry.AspNetCore" Version="3.5.0" /> -->
        <PackageReference Include="Sentry.Serilog" Version="3.5.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    </ItemGroup>

</Project>
```

Logger configuration:

```csharp
Log.Logger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .MinimumLevel.Debug()
    .WriteTo.Console()
    .WriteTo.Sentry( o =>
    {
        // Required in Serverless environments
        // o.FlushOnCompletedRequest = true; Won't compile with SentrySerilogOptions expected, as it is implemented on SentryAspNetCoreOptions
        o.Debug = true;
        o.MinimumBreadcrumbLevel = LogEventLevel.Debug;
        o.AttachStacktrace = true;
        o.SendDefaultPii = true;
    })
    .CreateLogger();
```

Logs:

```
Info: Capturing event.
  Debug: Running processor on exception: Testing Sentry from Lambda!
  Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
  Debug: Running main event processor on: Event 33fe714ba3f34844ba172d6e1901d8bc
  Error: An error occurred when capturing the event System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at System.Threading.SemaphoreSlim.Release()
   at Sentry.Internal.BackgroundWorker.EnqueueEnvelope(Envelope envelope) in /_/src/Sentry/Internal/BackgroundWorker.cs:line 68
   at Sentry.SentryClient.CaptureEnvelope(Envelope envelope) in /_/src/Sentry/SentryClient.cs:line 246
   at Sentry.SentryClient.DoSendEvent(SentryEvent event, Scope scope) in /_/src/Sentry/SentryClient.cs:line 231
   at Sentry.SentryClient.CaptureEvent(SentryEvent event, Scope scope) in /_/src/Sentry/SentryClient.cs:line 77.
```

Looks like an envelope is getting queued up after the worker has already been disposed?

**Comment by IhorKochetov** [comment] 2021-06-24 11:40
To add more context, that's the code of the deployed Lambda:

`public class Function
    {
        public Function()
        {
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .MinimumLevel.Debug()
                .WriteTo.Console()
                .WriteTo.Sentry( o =>
                {
                    o.Debug = true;
                    o.MinimumBreadcrumbLevel = LogEventLevel.Debug;
                    o.AttachStacktrace = true;
                    o.SendDefaultPii = true;
                })
                .CreateLogger();
        }
        
        public async Task Handler()
        {
            Log.Information("Starting body");

            Log.Information("Before exception");
            
            try
            {
                throw new ApplicationException("Testing Sentry from Lambda!");
            }
            catch (Exception e)
            {
                Log.Error(e, "Look what I've found!");
                throw;
            }
            
        }`

With csproj using those:

`<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
	    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
	    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
	    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.0.0" />
    <PackageReference Include="AWSSDK.ECS" Version="3.7.0.11" />
  </ItemGroup>
  </Project>`

**Comment by bruno-garcia** [comment] 2021-06-25 18:58
Related to: #321 

The Serilog provider is getting disposed:

https://github.com/getsentry/sentry-dotnet/blob/241ec58970cd1a9edbf804dcce577a0d2193a9f9/src/Sentry.Serilog/SentrySink.cs#L168

We should probably just Flush there and avoid disposing. Similar to #599 


A work around is to flush before rethrowing:

```
try
{
    throw new ApplicationException("Testing Sentry from Lambda!");
}
catch (Exception e)
{
    Log.Error(e, "Look what I've found!");
    await SentrySdk.FlushAsync(TimeSpan.FromSeconds(2));
    throw;
}
```

It's still going to log an error because the UnhandledException will try to capture that same exception (it was rethrown).
So to work around that, change the init to:

```
.WriteTo.Sentry( o =>
{
    // Add this:
    // We'll capture all exceptions on the top of the function manually:
    o. DisableAppDomainUnhandledExceptionCapture()
})
```

**Comment by IhorKochetov** [comment] 2021-06-29 14:08
Hey, thanks for looking into it!

So, am I understanding it correctly, that this workaround would only work for exceptions we caught and we wouldn't get any `UnhandledExceptions` in this manner?

I mean, this is better then nothing, but I would love to catch unhandled exceptions via Sentry too, that's like one of the big advantages SDK provides (out of the box), in my opinion. Code above is obviously just an example to reproduce a problem, not a real production code we expect to run / handle.

Is it just suggested as a temporary workaround and we should expect a proper fix for this going forward? Any ETA on it?

**Comment by Tyrrrz** [comment] 2021-06-29 16:40
If I understand correctly (and @bruno-garcia can correct me if I'm wrong), we'd still require an explicit flush regardless since we have no way of detecting whether the lambda request has finished already. The bug with the `ObjectDisposedException` will get fixed, but you'll still need to flush at the end of the request to ensure that all events are sent to Sentry in time.

> 1\. So would you suggest calling `SentrySdk.FlushAsync()` every time we do `Log.Something()`? Or it should be enough to call it once near the end of the lambda body/handler, something like wrapping it all into a try-finally with 'flushing' happening in the finally block? (and we are safe calling multiple Log.Something in between, if we wish to do so)?

Near the end of the lambda body/handler inside of `finally` block. `Log.Something(...)`, which internally translates to `SentrySdk.CaptureEvent(...)` simply adds an item to a background queue and returns immediately, it doesn't actually send anything to Sentry. Calling flush blocks (asynchronously) until the queue is emptied and all events are pushed to the underlying transport and delivered to Sentry's ingest. In other words, it is safe to have multiple `Log.Something(...)` calls in between. Calling flush after every event will likely be very undesirable because then every attempt to log something will have the additional I/O overhead of sending data over the wire. It's much more efficient to collect all events and then flush them at the end of the lambda request.

> 2\. Once again, the point of using Serilog for us here was to abstract from SentrySDK, and we even put the init code into a separate shared library to be the same everywhere / referenced and called from each lambda. Having to call `Skd.Flush()` in every lambda we have would kind of defeat the purpose of all that hiding and abstracting away 😢

If you have some kind of abstraction on top of AWS Lambda, you could probably put flush there 🤔

**Comment by IhorKochetov** [comment] 2021-06-30 14:16
Thanks @Tyrrrz 

>we'd still require an explicit flush regardless since we have no way of detecting whether the lambda request has finished already

After re-reading the thread I feel like @bruno-garcia suggested flush should be called inside of the Dispose of the Serilog/Sink. Which seems like should cover for the scenario discussed (one-time flush at the end of the Lambda stack decomposition)

So as soon as that's implemented/released, workaround with calling flush directly from the app code shouldn't be needed, it feels like?

**Comment by IhorKochetov** [comment] 2021-07-01 15:21
Alright, so flushing at the end of the Lambda body worked 👍  

Is probably not optimal in a way, that when you're actually 'done' with the business logic of the lambda, you're still keep running (and paying for) the lambda until the events are flushed out to Sentry (which maybe not a big of a price to actually get the information about errors, but still)


What I also tried after I succeeded with calling flush directly, is to implement the proposed fix myself. So I referenced the sources for the Sentry.Serilog and made this change to a `Dispose()` method in a `SentrySink.cs`:

```
        public void Dispose()
        {
            Console.WriteLine("Sink Disposed was called");
            var hub = _hubAccessor();
            if (hub == null || !hub.IsEnabled)
            {
                Console.WriteLine("Hab is null - {0}, hub isn't enabled - {1}", hub is null, !hub.IsEnabled);

                return;
            }

            Console.WriteLine("Calling flush");
            hub.FlushAsync(TimeSpan.FromSeconds(2))
                .GetAwaiter().GetResult();
            Console.WriteLine("Flush has returned");
        }
```

Which had no effect at all, unfortunately. As you can see, I even tried to 'debug' it by logging some of the steps, and I never even got those messages printed. So either Dispose wasn't called at all, or Console wasn't working, I am not sure, but no errors were reported to Sentry, unfortunately.

That's the output I managed to collect:
```
 ...
  | 2021-07-01T17:23:09.542+03:00 | Debug: Configuring the scope.
  | 2021-07-01T17:23:12.162+03:00 | [14:23:11 ERR] Application Error Goes Here
  | 2021-07-01T17:23:12.162+03:00 | Amazon.DynamoDBv2.Model.ResourceNotFoundException: Requested resource not found
  | 2021-07-01T17:23:12.162+03:00 | ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
  -- some more callstacks are going here --

  | 2021-07-01T17:23:12.220+03:00 | Debug: Failed to report an error on a session because there is none active.
  | 2021-07-01T17:23:12.240+03:00 | Info: Capturing event.
  | 2021-07-01T17:23:12.262+03:00 | Debug: Running processor on exception: Requested resource not found
  | 2021-07-01T17:23:12.299+03:00 | Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
  | 2021-07-01T17:23:12.500+03:00 | Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
  | 2021-07-01T17:23:12.639+03:00 | Debug: Running main event processor on: Event 9c800b0161024a0f922d061b0d29059a
  | 2021-07-01T17:23:12.682+03:00 | Debug: Envelope queued up.
  | 2021-07-01T17:23:12.719+03:00 | Debug: Configuring the scope.
  | 2021-07-01T17:23:13.279+03:00 | Debug: Envelope 9c800b0161024a0f922d061b0d29059a handed off to transport. #1 in queue.
  | 2021-07-01T17:23:13.302+03:00 | [14:23:13 INF] Application Info goes here (and we are going to exit lambda soon here)
  | 2021-07-01T17:23:13.339+03:00 | Debug: Configuring the scope.
  | 2021-07-01T17:23:13.361+03:00 | END RequestId: 7b06f4b8-a370-422a-8473-25031a08e11f
  | 2021-07-01T17:23:13.361+03:00 | REPORT RequestId: 7b06f4b8-a370-422a-8473-25031a08e11f Duration: 3941.49 ms Billed Duration: 3942 ms Memory Size: 256 MB Max Memory Used: 105 MB Init Duration: 477.03 ms

```

Actually, not each lambda run even gets as far as `Debug: Envelope 9c800b0161024a0f922d061b0d29059a handed off to transport. #1 in queue.`

Some end even before that call.

And from the successful logs I've seen (when called Flush directly), it looks like there should be a few more:

```
...
  | 2021-07-01T16:07:26.665+03:00 | Info: Capturing event.
  | 2021-07-01T16:07:26.685+03:00 | Debug: Running processor on exception: Requested resource not found
  | 2021-07-01T16:07:26.726+03:00 | Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
  | 2021-07-01T16:07:26.907+03:00 | Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
  | 2021-07-01T16:07:27.083+03:00 | Debug: Running main event processor on: Event b265b129887d4120ace526ffcd7ac6f8
  | 2021-07-01T16:07:27.143+03:00 | Debug: Envelope queued up.
  | 2021-07-01T16:07:27.163+03:00 | Debug: Configuring the scope.
  | 2021-07-01T16:07:27.604+03:00 | [13:07:27 INF] App Info here
  | 2021-07-01T16:07:27.643+03:00 | Debug: Configuring the scope.
  | 2021-07-01T16:07:27.705+03:00 | Debug: Tracking depth: 1.
  | 2021-07-01T16:07:27.883+03:00 | Debug: Envelope b265b129887d4120ace526ffcd7ac6f8 handed off to transport. #1 in queue.
  | 2021-07-01T16:07:28.126+03:00 | Debug: Envelope b265b129887d4120ace526ffcd7ac6f8 successfully received by Sentry.
  | 2021-07-01T16:07:28.143+03:00 | Debug: Signaling flush completed.
  | 2021-07-01T16:07:28.144+03:00 | Debug: Successfully flushed all events up to call to FlushAsync.
  | 2021-07-01T16:07:28.163+03:00 | END RequestId: b461c4dc-789a-45be-be89-71be84d0f8a6

```

Any thoughts on this? Anything catches your eyes I maybe doing wrong here?

**Comment by Tyrrrz** [comment] 2021-07-02 17:36
> Is probably not optimal in a way, that when you're actually 'done' with the business logic of the lambda, you're still keep running (and paying for) the lambda until the events are flushed out to Sentry (which maybe not a big of a price to actually get the information about errors, but still)

I mean, you still have to do it at some point, either immediately or after the request ended, but the I/O is still going to be there regardless 😉 

> So either Dispose wasn't called at all, or Console wasn't working, I am not sure, but no errors were reported to Sentry, unfortunately.

I'm not sure if that `Dispose` is called, to be honest. It might be that Lambda shuts down the process before it can even execute. As for `Console`, try using `_options.DiagnosticLogger?.LogDebug(...)` instead. Stdout writes might be redirected which could prevent them from showing up for one reason or another.

> `Debug: Envelope b265b129887d4120ace526ffcd7ac6f8 successfully received by Sentry.`

Yes, this is the log entry that signifies that an envelope has been fully dispatched to Sentry.

**Comment by bruno-garcia** [comment] 2022-04-27 21:51
We're going to focus on Lambda through #730 so closing this as it hasn't gotten any update

**Closed by bruno-garcia** 2022-04-27 21:51 UTC
Labels: bug, AWS Lambda, Serilog, Serverless, Platform: .NET
