### ISSUE TITLE
Data persisting after scope dispose

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#50] opened 2018-07-17 18:04 UTC
I updated to preview 3 and am using the following code in an ASP.Net Core 2.1 controller function:

```c#
SentrySdk.CaptureMessage("test a");

using (SentrySdk.PushScope())
{
    SentrySdk.ConfigureScope(o =>
    {
        o.SetExtra("NewScope", true);
    });

    SentrySdk.CaptureMessage("test b");
}

SentrySdk.CaptureMessage("test c");
```

"test a" has no additional data.  Both "test b" and "test c" have 'NewScope: true' in the additional data.  I would expect "test c" to not include this.

I was not able to reproduce in a console app, just Asp.Net core.  I also updated the controller to include "[FromServices] IHub sentryContext", and updated "SentrySdk" to use "sentryContext" and noted the same behavior.

**Comment by bruno-garcia** [comment] 2018-07-18 10:36
The reason this happens on ASP.NET Core is that the middleware [`locks` the scope](https://github.com/getsentry/sentry-dotnet/blob/433134ab3c387fe84df0e40e9e01d3ec0149fc11/src/Sentry.AspNetCore/SentryMiddleware.cs#L63) in order not to loose the log messages that happen throughout that request. The obvious side effect is that the manual control of scopes also stops working.

This will need some thinking now. Perhaps have the scope-locking feature only affect the logging integration.

**Comment by lunim** [comment] 2018-07-18 14:37
Okay, thanks.  I am seeing the issue in a console app and a .Net standard library.

**Comment by lunim** [comment] 2018-07-18 16:23
Thanks for the follow-up!

**Comment by lunim** [comment] 2018-08-27 21:37
I don't know if this is a related effect, but it seems that breadcrumbs always persist in an ASP.Net application.  For example, if I report an issue that has 100 breadcrumbs, then a few hours later another issue is reported, the same 100 breadcrumbs are reported.

The down-side being is that events will be fairly large, and might contains much more data than related to sift through.

**Comment by bruno-garcia** [comment] 2018-08-28 10:03
The breadcrumbs added up to the point where the Sentry middleware kicks in would stay the same and be sent with all requests. 

Are these crumbs added by the logging integration? If so, aren't they all related to that same request? With the exception of what was logged before like the messages about the application starting up.

I noticed that and thought of adding an option to clear breadcrumbs in the middleware. It means that the breadcrumb trail would start at the beginning of the pipeline (after kestrel, skipping anything that was added before Sentry). Other than that I guess it's fine tuning what actually generates the breadcrumbs.

If the logger is too verbose, tuning the log level for example [with this setting](https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry.Extensions.Logging/SentryLoggingOptions.cs#L20).

**Comment by lunim** [comment] 2018-08-28 14:34
Yes, I am seeing crumbs from both the logging and the SentrySdk.AddBreadcrumb static method.

I have a background worker in my ASP.Net app which logs status messages and the history from application start gets included with every capture.  I do have breadrumbs relating to the current request though.

I am using the [FromServices] sentry reference in my controller when calling Capture exception.

**Comment by bruno-garcia** [comment] 2018-08-28 14:40
I think I see the issue.

Would an API like:

```csharp
hub.ClearBreadcrumbs();
```

resolve the issue?
I could have an opt-in that would call this method in the ASP.NET Core integration, inside the middleware.

That means that if a crash happens before a request reached the middleware (i.e: app starting for example), all those useful breadcrumbs are included.
If on the other hand a request reaches the middleware, we start with a clean trail.

At what point to you start your background worker?

**Comment by lunim** [comment] 2018-08-28 15:26
That should work.  The background worker starts at application start and does some work on a timed interval.

**Comment by bruno-garcia** [comment] 2018-08-28 17:09
Is it a `IHostedService`? Just curious now ;)

**Comment by lunim** [comment] 2018-08-28 17:58
@bruno-garcia Yes, it's a service implementing `BackgroundService` following this article: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#implementing-ihostedservice-with-a-custom-hosted-service-class-deriving-from-the-backgroundservice-base-class

I had a SentrySdk.AddBreadcrumb to indicate the start each update within the worker.  Without changing that, every captured event in Sentry basically had 100 breadcrumbs, with most of them indicating the start of the loop.  I still had the relevant breadcrumbs, but just a lot of extra noise.  I cleaned up the code to not add those crumbs since then.

**Comment by bruno-garcia** [comment] 2018-10-08 14:54
@lunim do you actually have a use case where a new scope would be pushed within the ASP.NET Core request? Or this came out while testing the API?
Just curious if this is a real issue right now.

**Comment by bruno-garcia** [comment] 2018-10-08 14:57
@lunim Another solution for this is to push a scope in your background worker. So it doesn't work on the scope which is root of all web requests. You could `PushScope` on `Start` and dispose it on Stop.

**Comment by lunim** [comment] 2018-10-13 18:19
> @lunim Another solution for this is to push a scope in your background worker. So it doesn't work on the scope which is root of all web requests. You could `PushScope` on `Start` and dispose it on Stop.

I'm now using PushScope around my background thread and it accomplished what I was looking for, thanks!

**Comment by bruno-garcia** [comment] 2018-10-15 08:37
@lunim yeah that's the way to go.
Considering the start of a _transaction_ is the web request, the current behaviour is the desired one.
For that reason I'll close this as this behaviour is by design.

**Closed by bruno-garcia** 2018-10-15 08:37 UTC
Labels: bug
