### ISSUE TITLE
X-Forwarded-For isn't used in transactions

### ISSUE THREAD

**Issue by juliancarrivick** [getsentry/sentry-dotnet#1576] opened 2022-04-15 10:04 UTC
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

5.0.9

### OS

Linux

### SDK Version

3.16.0

### Steps to Reproduce

1. Following [docs](https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/troubleshooting/#user-ip-address-in-sentry-shows-up-as-the-server-ip) as described in #258 to [`UseForwardedHeaders`](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0) (I'm actually hosted on [Fly](https://fly.io) and using the `Fly-Client-IP` header, but I don't think this should make a difference)
2. Add `UseSentryTracing()` right after `UseRouting()` in my Startup.cs
3. Set TracesSampleRate to 1.0 to ensure all transactions are recorded
4. Send HTTP request to endpoint that deliberately throws an exception with the `Fly-Client-IP` header set to something noticable

### Expected Result

- Error event has `User.IpAddress` set to the value set in the header
- Transaction `User.IpAddress` set to the value set in the header

### Actual Result

- ✔ Error event has `User.IpAddress` set to the value set in the header
- ❌ Transaction `User.IpAddress` is not set to the value set in the header, but the IP of the requesting client.

**Comment by bruno-garcia** [comment] 2022-04-20 20:56
`X-Forwarded-For` is the actual industry standard and what ASP.NET Core supports.
It's not surprising to me that `Fly-Client-IP` is affecting `User.IpAddress`, could you please clarify why you had that expectation? If somehow we mention on the docs, we should amend that.

**Comment by mattjohnsonpint** [comment] 2022-04-21 00:36
@bruno-garcia - I see that [Fly does set `X-Forwarded-For`](https://fly.io/docs/reference/services/#http) also.  So I think the point about `Fly-Client-IP` isn't related.

@juliancarrivick - I think you're just saying that `X-Forwarded-For` appears to be picked up for errors but not for transactions, is that right?

**Comment by mattjohnsonpint** [comment] 2022-04-21 00:44
If so, the order in which you put `app.UseForwardedHeaders();` and `app.UseSentryTracing();` will matter.   I *think* you want `UseForwardedHeaders` to come first, but it would be great if you could try it and let us know.  Thanks.

**Comment by juliancarrivick** [comment] 2022-04-21 01:37
Thanks both. Yes @mattjohnsonpint I am saying that `X-Forwarded-For` is being picked up for errors but not transactions. I tried to have a poke through the source code to see if I could see why but I was unable to find the spot where the transaction middleware sets the user/IP. I'll try the below changes and report back (will probably be tomorrow Aus time).

I currently configure [`ForwardedHeaderOptions`](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#forwarded-headers-middleware-options-1) to use `Fly-Client-IP`, I can try to remove that bit to see if it the default of `X-Forwarded-For` makes a difference, but I think it's probably unlikely given using `Fly-Client-IP` works for errors.
``` c#
services.Configure<ForwardedHeadersOptions>(options =>
{
    // See https://fly.io/docs/reference/runtime-environment/#fly-client-ip
    options.ForwardedForHeaderName = "Fly-Client-IP";
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor;
});
```

I am currently configuring `app.UseForwardedHeaders()` first as recommended by the [MS Docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#forwarded-headers-middleware-order-1). I can try to switch this order, but again I don't think it will make a difference given how this works.
``` c#
    public void Configure(IApplicationBuilder app, IHostEnvironment env, ILogger<Startup> logger)
    {
        logger.LogInformation($"Starting in {env.EnvironmentName} environment");

        app.UseForwardedHeaders();

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        if (!env.IsDevelopment())
        {
            app.UseHttpsRedirection();
        }

        app.UseRouting();
        app.UseSentryTracing();
        app.UseCors();
        app.UseAuthentication();
        app.UseAuthorization();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
    }
```

My guess is `app.UseSentryTracing()` isn't using `HttpContext.Connection.RemoteIpAddress` to populate the user details, since that is what the ForwardedHeaders middleware is updating (see [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#forwarded-headers-1). But I was unable to confirm this by looking through the source code.

**Comment by mattjohnsonpint** [comment] 2022-04-21 16:58
Just checking, but I assume that you have the `SendDefaultPii` option set to `true`?

**Comment by mattjohnsonpint** [comment] 2022-04-21 22:50
I can't reproduce your results.  I successfully get the user IP address as set by the header.  Here's my minimal repro attempt:

```csharp
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.Extensions.DependencyInjection;

namespace WebApplication1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebHost.CreateDefaultBuilder(args)
                .UseSentry(o =>
                {
                    o.Dsn = "...My DSN...";
                    o.Debug = true;
                    o.SendDefaultPii = true;
                    o.TracesSampleRate = 1.0;
                })
                .ConfigureServices(services =>
                {
                    services.Configure<ForwardedHeadersOptions>(options =>
                    {
                        options.ForwardedForHeaderName = "Fly-Client-IP";
                        options.ForwardedHeaders = ForwardedHeaders.XForwardedFor;
                    });
                })
                .Configure(app =>
                {
                    app.UseForwardedHeaders();
                    app.UseRouting();
                    app.UseSentryTracing();

                    app.UseEndpoints(endpoints =>
                    {
                        endpoints.MapGet("/", async context => { await context.Response.WriteAsync("Hello World!"); });
                    });
                });

            builder.Build().Run();
        }
    }
}
```

I then used postman to make the request, so I could manually set the `Fly-Client-IP` header:

![image](https://user-images.githubusercontent.com/1396388/164563596-b52908fc-a863-4a6d-a9bf-9aff8c6165f7.png)

When I check the transaction coming through to Sentry, I see the IP address I specified in the header.

![image](https://user-images.githubusercontent.com/1396388/164563807-e9cb2764-a7df-44c8-99e6-ee316069c63b.png)

I suggest checking everything thoroughly.  I'm closing this for now.  If you can get an example like this to show the wrong result, let us know and we'll re-open this issue.  Thanks.

**Closed by mattjohnsonpint** 2022-04-21 22:50 UTC
Labels: question, Platform: .NET

**Comment by juliancarrivick** [comment] 2022-04-22 01:03
Hi @mattjohnsonpint, thanks for taking a look. I feel like a bit of a fool now... I thought I had tested this locally with explicitly setting the `Fly-Client-IP` header, but apparently not because trying it now has worked. 

Something funky is going on in the Fly environment I think, I can see the headers in the transaction for my staging environment, but it seems `UseForwardedHeaders` isn't triggering for some reason (incorrect IP for events too). This happens regardless whether I'm using `Fly-Client-IP` or `X-Forwarded-For`, so it might be pointing to an issue in how Fly passes these headers given it's working locally. Thanks for your help and sorry to waste your time 😅 I will see if I can get help on Fly's forums (I'll link the topic I eventually make here to maybe help a future visitor 🙂)

**Comment by mattjohnsonpint** [comment] 2022-04-22 02:08
No worries on the time.  I joined sentry a couple of months ago, so debugging issues like these really help me understand the internals better, regardless of the outcome. 😄

**Comment by juliancarrivick** [comment] 2022-04-22 07:14
Glad it wasn't all a waste of time then 🙂 

I have now posted this issue on Fly's forums: https://community.fly.io/t/asp-net-core-unable-to-use-forwarded-headers/4832. I'm feeling less of a fool now as this seems to be some wierd interaction between ASP.NET Core and the Fly infrastructure!

**Comment by juliancarrivick** [comment] 2022-04-22 07:42
Just a quick note that I figured out what was going on, `KnownNetworks` or `KnownProxies` needs to be configured for proxies situated on anything other than loopback addresses to work. This specified in the MS docs, but isn't very prominant which is why I missed it. And why it worked locally but not on Fly 🙂 Hope this helps someone else.
