### ISSUE TITLE
Upload symbols from primary output (bin) folder, not intermediate output (obj) folder

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#2260] opened 2023-03-28 14:02 UTC
There's a lot of intermediate debug files being uploaded to Sentry during build. From my past testing, these do not actually provide any value to symbolication and shouldn't be uploaded. See some more details here: https://github.com/getsentry/sentry-dotnet/pull/2191#pullrequestreview-1307895569

I propose we only upload final files from the Release folder during a build.

After this is resolved, enable the tests here: `test/sentry-cli-integration.Tests.ps1`

**Comment by mattjohnsonpint** [comment] 2023-03-28 14:22
I've gone back and forth on this one.  The problem is that some platforms need native debug symbols also.  But I agree we should probably change how this is done so it isn't so arbitrary.  We should check each platform.   Use bin by default, and then add others where needed only.

Thanks for raising the issue!

**Comment by mattjohnsonpint** [comment] 2023-03-28 16:27
Maybe we only need managed pdbs, and then native _symbols_ for specific platform targets, and can deliberately skip executables and native libraries?

**Comment by mattjohnsonpint** [comment] 2023-04-28 22:20
There's another problem with uploading the intermediate files, which is that depending on project structure, we may not be uploading dependencies from referenced libraries.

If those libraries are published to nuget or some other symbol store, that's one thing.  But it's perfectly reasonable (especially in some enterprise shops) to have assembly references to `.dll` files in some other random directory that are not published anywhere.

This would be resolved by switching to the primary output (`/bin`) folder.

**Closed** 2023-05-02 02:36 UTC
Labels: enhancement, Platform: .NET
