### ISSUE TITLE
Reported excp source StackTrace line does not match actual excp source line

### ISSUE THREAD

**Issue by vmandic** [getsentry/sentry-dotnet#2322] opened 2023-04-21 16:13 UTC
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

3.1.416

### OS

Linux

### SDK Version

3.30.0

### Steps to Reproduce

Hi. 

We enabled uploading source and symbols using Portable PDB netcoreapp31 (publish in docker), and we are observing non-matching src stacktrace line with actual excp line. Example in screenshot, line highlighted is a return statement which has nothing with the Exception that is thrown:

We do the build inside docker like:

```
ENV SENTRY_LOG_LEVEL=info

RUN dotnet publish -c release -o /app -r $PLATFORM -p:UseSentryCLI=true -p:SentryOrg=$ORGNAME  \
    -p:SentryProject=$PROJNAME -p:SentryUploadSymbols=true -p:SentryUploadSources=true  \
    --self-contained true --no-restore -p:PublishReadyToRun=true -p:DebugType=Portable -p:DebugSymbols=true
```

Should changing to `DebugType=Full` be of any help?

If it helps:

ISSUE ID: 3894189831
PROJECT ID: 5239187

We are NOT self-hosted you can reach me out private to give out subdomain ID.

We upgraded from 3.13 SDK and did not have issues in showing the exact correct matching line where the exception occurs. We did not used PDB and source upload, we only had stacktrace info but it was correct.

### Expected Result

Highlighted line should be showing the `throw CreateMyException()` L763.

### Actual Result

The actual exception is explicitly thrown 13 lines after in L763. The highlighted code is not relevant to the exception.

![image](https://user-images.githubusercontent.com/1390895/233682143-726dcce7-cbba-49f7-a9f8-f9bb7148400e.png)

part of logs with our exe REST WEB API being built and reported with Sentry in docker:

```log
#33 60.34   RedactedProjectName -> /source/RedactedProjectName/bin/linux-musl-x64/release/netcoreapp3.1/linux-musl-x64/RedactedProjectName.dll
#33 60.44     INFO    2023-04-21 11:42:22.049859105 +00:00 sentry-cli was invoked with the following command line: "/root/.nuget/packages/sentry/3.30.0/tools/sentry-cli-Linux-x86_64" "info" "--no-defaults"
#33 162.3   Some ReadyToRun compilations emitted warnings, indicating potential missing dependencies. Missing dependencies could potentially cause runtime failures. To show the warnings, set the PublishReadyToRunShowWarnings property to true.
#33 166.9   RedactedProjectName -> /app/
#33 166.9   Preparing to upload debug symbols and sources to Sentry for RedactedProjectName (release/netcoreapp3.1)
#33 166.9     INFO    2023-04-21 11:44:08.525740235 +00:00 sentry-cli was invoked with the following command line: "/root/.nuget/packages/sentry/3.30.0/tools/sentry-cli-Linux-x86_64" "dif" "upload" "--org" "RedactedProjectName" "--project" "RedactedProjectName-api" "--include-sources" "obj/linux-musl-x64/release/netcoreapp3.1/linux-musl-x64/"
#33 166.9     INFO    2023-04-21 11:44:08.526156313 +00:00 Issuing a command for Organization: RedactedProjectName Project: RedactedProjectName-api
#33 167.5   > Found 9 debug information files (4 with embedded sources)
#33 167.6   > Resolved source code for 1 debug information file
#33 167.6   > Prepared debug information files for upload
#33 168.3   > Uploaded 2 missing debug information files
#33 168.5   > File upload complete:
#33 168.5   
#33 168.5     PENDING 6de92202-c49f-4a5b-a2da-6f8285d2c8f2-df7452e3 (RedactedProjectName.pdb; unknown debug companion)
#33 168.5     PENDING 6de92202-c49f-4a5b-a2da-6f8285d2c8f2-df7452e3 (RedactedProjectName.pdb; unknown sources)
```

part of logs with our lib used by exe REST WEB API where the mismatch occurs:

```log
#33 37.15   RedactedProjectNameLib -> /source/RedactedProjectNameLib/bin/linux-musl-x64/release/netstandard2.0/RedactedProjectNameLib.dll
#33 37.21     INFO    2023-04-21 11:41:58.818782460 +00:00 sentry-cli was invoked with the following command line: "/root/.nuget/packages/sentry/3.30.0/tools/sentry-cli-Linux-x86_64" "info" "--no-defaults"
#33 37.81   Preparing to upload debug symbols and sources to Sentry for RedactedProjectNameLib (release/netstandard2.0)
#33 37.82     INFO    2023-04-21 11:41:59.428935237 +00:00 sentry-cli was invoked with the following command line: "/root/.nuget/packages/sentry/3.30.0/tools/sentry-cli-Linux-x86_64" "dif" "upload" "--org" "RedactedProjectName" "--project" "RedactedProjectName-api" "--include-sources" "obj/linux-musl-x64/release/netstandard2.0/"
#33 37.82     INFO    2023-04-21 11:41:59.429024215 +00:00 Issuing a command for Organization: RedactedProjectName Project: RedactedProjectName-api
#33 38.36   > Found 1 debug information file
#33 38.42   > Resolved source code for 1 debug information file
#33 38.42   > Prepared debug information files for upload
#33 39.16   > Uploaded 2 missing debug information files
#33 39.34   > File upload complete:
#33 39.34   
#33 39.34     PENDING 9fb191da-e926-43fd-8823-ce5bc7b5795b-8a378395 (RedactedProjectNameLib.pdb; unknown sources)
#33 39.34     PENDING 9fb191da-e926-43fd-8823-ce5bc7b5795b-8a378395 (RedactedProjectNameLib.pdb; unknown debug companion)
```

**Comment by mattjohnsonpint** [comment] 2023-04-23 18:14
Thanks for reporting, but I'm not exactly sure how this is happening.  It may take a bit of cooperation to get a full reproduction so we can investigate further.  Do you feel like you could provide a small project that reproduces the problem?

I was able to find the issue you referenced, and it doesn't shed a whole lot of light on the problem, other than I do indeed see that the highlighted line is a return statement, not likely something that would throw an exception.

An initial thought - I see from the logs you provided, there's a messages about `ReadyToRun` warnings.  It would be good to see those warnings, to see if they're possibly relevant here.  You might consider trying without `-p:PublishReadyToRun=true` to see if it makes any difference.  We've not done a whole lot of testing with `ReadyToRun`, so it's possible that there's something we need to do on our side to accommodate it.  

You asked about `DebugType` - Since you're running on Linux, there's no difference between `full` and `portable` with regard to Sentry.  However, since you're on .NET Core 3.1, there's some performance overhead by using `full`, so I don't recommend it.  That was resolved with .NET 6.  See the notes at https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-options/code-generation#debugtype

You should be able to remove `-p:DebugType=Portable -p:DebugSymbols=true` and the defaults should work fine.

**Comment by mattjohnsonpint** [comment] 2023-04-23 20:01
FWIW, the issue is showing the same line numbers reported directly by .NET.  You can see this on the Sentry issue details page by clicking the "unsymbolicated" and "raw stack trace" options on the stack trace.  The result is sent directly by the SDK from the stack trace provided by .NET at runtime.  Since the pdb files are deployed with the app, you get filenames and line numbers at runtime.

Also, there are many other reports of .NET occasionally giving the wrong line numbers.  Some of these have been fixed over time by the .NET team, and some have not.  Here's one of particular interest:
https://stackoverflow.com/questions/37072185/wrong-line-numbers-in-stack-trace

Of the three answers there, the one about ReadyToRun is interesting, and so is the one about the SCOM agent (not sure if that's applicable for you or not).

**Comment by mattjohnsonpint** [comment] 2023-04-23 20:08
It could also possibly be related to https://github.com/dotnet/runtime/issues/44986 or another similar issue.

**Comment by vmandic** [comment] 2023-04-25 08:11
Thanks for coming back at me Matt.

Unfortunately I am not in a position to provide a min repro. What I can tell you is this does not occur often, it is more of an exception and I'd safely say not up to you guys but dotnet itself per related issue you linked before.

What I can tell you, if its worth having open this issue, is that we are just testing an upgrade of project from netcoreapp3.1 to net7 and I will see we get issues reported there with this problem. Maybe best close the issue also and I can come back at you with more info later as this could take up to 10 days or more for a confirmation. 

(We are not opting to the new trimming feature also... that's a different kind of beast with newer dotnet!)

We still have to address warnings also.

**Comment by mattjohnsonpint** [comment] 2023-04-25 14:51
Sounds good.  I'll close this then. Feel free to re-open if it makes sense later. 

Good luck with your migration! 🙂

**Closed by mattjohnsonpint** 2023-04-25 14:51 UTC
Labels: bug, Platform: .NET
