### ISSUE TITLE
MongoDB integration

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3730] opened 2024-11-05 22:35 UTC
### Problem Statement

See: https://x.com/ethansteininger/status/1853878751555113116?s=46&t=PP1rx-wam39ljTQ5uqe7Dg

https://develop.sentry.dev/sdk/telemetry/traces/modules/queries/

### Solution Brainstorm

Can we leverage this from OTel? Or do we need a `Sentry.MongoDB`?

**Comment by jamescrosswell** [comment] 2024-11-05 23:12
We had some prior discussions on this:
- https://github.com/getsentry/sentry-dotnet/issues/2578

**Comment by jamescrosswell** [comment] 2024-11-05 23:13
Duplicate of https://github.com/getsentry/sentry-dotnet/issues/2578

**Closed by jamescrosswell** 2024-11-05 23:13 UTC
Labels: Feature, Product: Starfish
